import 'package:drift/drift.dart';

import 'package:daredevil/data/database/app_database.drift.dart';
import 'package:daredevil/data/database/tables/event_tables.drift.dart';

/// 事件行事曆相關資料存取
mixin EventDaoMixin on $AppDatabase {
  // ==================================================
  // 事件行事曆操作
  // ==================================================

  /// 取得日期範圍內的事件
  Future<List<StockEventEntry>> getEventsInRange(
    DateTime start,
    DateTime end, {
    List<String>? symbols,
  }) {
    final query = select(stockEvent)
      ..where(
        (t) =>
            t.eventDate.isBiggerOrEqualValue(start) &
            t.eventDate.isSmallerOrEqualValue(end),
      )
      ..orderBy([(t) => OrderingTerm.asc(t.eventDate)]);

    // null＝不過濾；空清單＝「過濾到空集合」只剩無 symbol 的個人備忘。
    // 不可把空清單當不過濾——預設 watchlistOnly 下，空自選使用者會
    // 反而看到全市場事件（2026-07-24 審查修復）。
    if (symbols != null) {
      query.where(
        (t) => symbols.isEmpty
            ? t.symbol.isNull()
            : (t.symbol.isIn(symbols) | t.symbol.isNull()),
      );
    }

    return query.get();
  }

  /// 新增事件
  Future<int> insertStockEvent(StockEventCompanion entry) {
    return into(stockEvent).insert(entry);
  }

  /// 批次新增事件(2026-08-01 smell 掃描 Tier 1:producers 重建動輒
  /// 百餘筆,逐筆 await 是 N+1;比照 [DividendDaoMixin.insertDividendData]
  /// 的 batch 慣例)
  Future<void> insertStockEvents(List<StockEventCompanion> entries) async {
    if (entries.isEmpty) return;
    await batch((b) {
      for (final entry in entries) {
        b.insert(stockEvent, entry);
      }
    });
  }

  /// 更新事件
  Future<void> updateStockEvent(int id, StockEventCompanion entry) {
    return (update(stockEvent)..where((t) => t.id.equals(id))).write(entry);
  }

  /// 刪除事件
  Future<void> deleteStockEvent(int id) {
    return (delete(stockEvent)..where((t) => t.id.equals(id))).go();
  }

  /// 讀取指定類型的全部自動事件（累積型 producer 的去重比對用）
  Future<List<StockEventEntry>> getAutoGeneratedEventsByType(String eventType) {
    return (select(stockEvent)..where(
          (t) => t.isAutoGenerated.equals(true) & t.eventType.equals(eventType),
        ))
        .get();
  }

  /// 刪除指定類型的系統自動產生事件
  ///
  /// 只刪除 [eventTypes] 指定的類型，不影響其他自動事件。
  /// 用於分類型同步（如只重建除權息事件而不影響股東會事件）。
  Future<void> deleteAutoGeneratedEventsByTypes(List<String> eventTypes) {
    return (delete(stockEvent)..where(
          (t) => t.isAutoGenerated.equals(true) & t.eventType.isIn(eventTypes),
        ))
        .go();
  }
}
