import 'package:drift/drift.dart';
import 'package:intl/intl.dart';

import 'package:daredevil/core/constants/api_config.dart';
import 'package:daredevil/core/constants/market_codes.dart';
import 'package:daredevil/core/exceptions/app_exception.dart';
import 'package:daredevil/core/utils/date_context.dart';
import 'package:daredevil/core/utils/logger.dart';
import 'package:daredevil/data/database/app_database.dart';
import 'package:daredevil/data/remote/tpex_client.dart';
import 'package:daredevil/data/remote/twse_client.dart';

/// 已拆開現金與配股的除權除息列 → 股利配發表的寫入列（本月同步與歷史回補
/// 共用），含列表的前收盤與除權息參考價（見 [_listedPrice]）。列表拆不出、
/// 尚未補明細的列（[ExRightResult.needsDetail]）不可傳入。
DividendDistributionCompanion dividendDistributionCompanion(
  ExRightResult row,
) => DividendDistributionCompanion.insert(
  symbol: row.symbol,
  exDate: row.exDate,
  cashDividend: row.cashDividend!,
  stockSharesPerThousand: row.stockSharesPerThousand!,
  closeBefore: Value(_listedPrice(row.closeBefore)),
  referencePrice: Value(_listedPrice(row.referencePrice)),
);

/// 列表上的前收盤與除權息參考價（已在庫列補價用，見
/// `AppDatabase.updateDividendDistributionPrices`）
DividendListedPrice dividendListedPrice(ExRightResult row) => (
  symbol: row.symbol,
  exDate: row.exDate,
  closeBefore: _listedPrice(row.closeBefore),
  referencePrice: _listedPrice(row.referencePrice),
);

/// 列表價格欄的存法：0 或負值當缺值存 null——還原因子是參考價 ÷ 前收盤，
/// 0 會讓因子變成 0 或無限大，存 null 讓讀取端判為缺價
double? _listedPrice(double? value) =>
    value != null && value > 0 ? value : null;

/// 股東會 + 除權除息同步器
///
/// 從 TWSE/TPEX 取得：
/// 1. 股東會日程寫入 StockEvent（eventType = SHAREHOLDER_MEETING，
///    [syncShareholderMeetings]）：上市的日期內嵌在 TWSE 已宣告股利回應，
///    上櫃取自 TPEx 股東會資料
/// 2. 除權除息計算結果寫入 DividendDistribution（[syncDistributions]）
///
/// 2 只管本月；歷史月份由 `DividendBackfiller` 回補（同一步驟、本月同步之後）。
///
/// 1 在 UpdateService._syncAuxiliaryData()（並行階段）呼叫，與
/// MarketIndexSyncer、TdccHoldingSyncer 同級；2 在更新步驟 6.6（上櫃候選補充
/// 之後、評分之前）依序執行。
class DividendSyncer {
  DividendSyncer({
    required AppDatabase database,
    TwseClient? twseClient,
    TpexClient? tpexClient,
    Duration detailCallDelay = const Duration(
      milliseconds: ApiConfig.dividendCallDelayMs,
    ),
  }) : _db = database,
       _twse = twseClient,
       _tpex = tpexClient,
       _detailCallDelay = detailCallDelay;

  final AppDatabase _db;
  final TwseClient? _twse;
  final TpexClient? _tpex;

  /// TWT49UDetail 呼叫間隔（測試傳 [Duration.zero]）
  final Duration _detailCallDelay;

  static final _dateFormat = DateFormat('yyyy-MM-dd');

  /// 同步股東會日程
  ///
  /// 各來源獨立 try/catch，單一來源失敗不影響其他；股東會事件的全市場重建
  /// 只在所有已嘗試來源皆成功時執行（見 Phase 3），避免部分失敗誤刪既有資料。
  /// [RateLimitException]／[NetworkException] 往上拋，由 UpdateService 處理。
  Future<ShareholderMeetingSyncResult> syncShareholderMeetings() async {
    var meetingEventsCreated = 0;
    final errors = <String>[];

    // 追蹤各股東會來源本輪是否失敗。Phase 3 的全市場刪除只有在「所有已嘗試的
    // 股東會來源皆成功」時才安全——否則 meetingCompanions 只含部分市場，
    // delete-then-rewrite 會清掉失敗來源上一輪正確寫入的事件且無法補回。
    var twseMeetingsFailed = false;
    var tpexMeetingsFailed = false;

    // 取得 DB 中所有已知股票（FK constraint — 過濾 1101B 等特別股）
    final knownStocks = await _db.getAllActiveStocks();
    final knownSymbols = knownStocks.map((s) => s.symbol).toSet();
    final meetingCompanions = <StockEventCompanion>[];

    // ==================================================
    // Phase 1: 上市股東會（TWSE 已宣告股利回應內嵌股東會日期）
    // ==================================================
    if (_twse != null) {
      try {
        final twseData = await _twse.getDeclaredDividends();
        for (final item in twseData) {
          if (!knownSymbols.contains(item.symbol)) continue;
          if (item.shareholderMeetingDate == null) continue;
          meetingCompanions.add(
            StockEventCompanion.insert(
              symbol: Value(item.symbol),
              eventType: 'SHAREHOLDER_MEETING',
              eventDate: item.shareholderMeetingDate!,
              title: '${item.symbol} ${item.companyName} 股東會',
              description: const Value(null),
              isAutoGenerated: const Value(true),
            ),
          );
        }
        AppLogger.info(
          'DividendSyncer',
          'TWSE 已宣告股利（取股東會）: ${twseData.length} 筆',
        );
      } on RateLimitException {
        rethrow;
      } on NetworkException {
        rethrow;
      } catch (e) {
        twseMeetingsFailed = true;
        AppLogger.warning('DividendSyncer', 'TWSE 已宣告股利（股東會）同步失敗', e);
        errors.add('TWSE 已宣告股利: $e');
      }
    }

    // ==================================================
    // Phase 2: 上櫃股東會（TPEX ap41_O）
    // ==================================================
    if (_tpex != null) {
      try {
        final meetings = await _tpex.getShareholderMeetings();
        for (final meeting in meetings) {
          if (!knownSymbols.contains(meeting.symbol)) continue;

          meetingCompanions.add(
            StockEventCompanion.insert(
              symbol: Value(meeting.symbol),
              eventType: 'SHAREHOLDER_MEETING',
              eventDate: meeting.meetingDate,
              title:
                  '${meeting.symbol} ${meeting.companyName} ${meeting.meetingType}',
              description: Value(_buildMeetingDescription(meeting)),
              isAutoGenerated: const Value(true),
            ),
          );
        }
        AppLogger.info('DividendSyncer', 'TPEX 股東會: ${meetings.length} 筆');
      } on RateLimitException {
        rethrow;
      } on NetworkException {
        rethrow;
      } catch (e) {
        tpexMeetingsFailed = true;
        AppLogger.warning('DividendSyncer', 'TPEX 股東會同步失敗', e);
        errors.add('TPEX 股東會: $e');
      }
    }

    // ==================================================
    // Phase 3: 寫入股東會 StockEvent（去重後）
    // ==================================================
    // deleteAutoGeneratedEventsByTypes 是全市場（不分 symbol/來源）刪除，故
    // 只有在所有已嘗試的股東會來源本輪皆成功時才可 delete-then-rewrite。若任一
    // 來源失敗，meetingCompanions 僅含成功來源的部分市場，此時重建會連同失敗
    // 來源上一輪正確寫入的事件一併清空且無法補回——改為略過本輪重建、保留既有
    // 事件，待下輪所有來源皆成功再重建。
    final meetingSourceFailed = twseMeetingsFailed || tpexMeetingsFailed;
    if (meetingCompanions.isNotEmpty && meetingSourceFailed) {
      AppLogger.warning('DividendSyncer', '部分股東會來源失敗，略過重建以保留既有事件');
      errors.add('股東會事件: 部分來源失敗，略過重建以保留既有資料');
    } else if (meetingCompanions.isNotEmpty) {
      try {
        // 去重：同一 symbol + 同一日期只保留一筆（TWSE 和 TPEX 可能重複）
        final uniqueMeetings = _deduplicateEvents(meetingCompanions);

        await _db.transaction(() async {
          // 只刪除 SHAREHOLDER_MEETING 類型的自動事件，不影響其他
          await _db.deleteAutoGeneratedEventsByTypes(const [
            'SHAREHOLDER_MEETING',
          ]);
          await _db.insertStockEvents(uniqueMeetings);
        });
        meetingEventsCreated = uniqueMeetings.length;
        AppLogger.info('DividendSyncer', '股東會事件寫入: $meetingEventsCreated 筆');
      } catch (e) {
        AppLogger.warning('DividendSyncer', '股東會事件寫入失敗', e);
        errors.add('股東會事件: $e');
      }
    }

    return ShareholderMeetingSyncResult(
      meetingEventsCreated: meetingEventsCreated,
      errors: errors,
    );
  }

  /// 同步本月的除權除息至股利配發表（dividend_distribution）
  ///
  /// 範圍＝本月初與今天往前 [ApiConfig.dividendSyncOverlapDays] 天中較早者，
  /// 至今天。先上櫃（1 次列表、不需明細），再上市（1 次列表）：「息」列
  /// 直接寫入；「權」「權息」列拆不開現金與配股，逐列查 TWT49UDetail——
  /// DB 已有該列（含只有現金增資、金額皆 0 的已處理列）就不再查。不在
  /// 股票主檔的代號在查明細之前略過（外鍵會讓整批寫入失敗）。
  ///
  /// 列表與明細合計最多 [maxCalls] 次，沒查到的明細留待下一輪
  /// （[DividendDistributionSyncResult.pendingDetails]）。每筆明細查到就
  /// 立刻寫入：中途被限流或斷線打斷，已查的不會丟。每次查明細前等
  /// [_detailCallDelay]。
  ///
  /// 一般失敗（列表不可信、單列明細不可信）記進 errors 後繼續；
  /// [RateLimitException]／[NetworkException] 往上拋——前者由 UpdateService
  /// 中止本輪，後者記錯誤後續跑。
  ///
  /// 各市場列表成功後記錄完整度事實（DAO `recordDividendListing`）：明細被
  /// 中斷也照記，未查的列以 pendingDetail 留在未解決清單；事實寫入失敗只進
  /// errors。
  ///
  /// [dataDate]：本輪更新的資料日（`UpdateService` 的 `ctx.normalizedDate`）。
  /// 列表日記 min(今天, [dataDate])——凌晨補跑時資料日是前一個交易日，
  /// 不可多宣稱一天。省略時為今天。
  Future<DividendDistributionSyncResult> syncDistributions({
    required DateTime today,
    required int maxCalls,
    DateTime? dataDate,
  }) async {
    final end = DateContext.normalize(today);
    final dataEnd = dataDate == null ? end : DateContext.normalize(dataDate);
    final listedThrough = dataEnd.isAfter(end) ? end : dataEnd;
    final monthStart = DateTime(end.year, end.month);
    final overlapStart = end.subtract(
      const Duration(days: ApiConfig.dividendSyncOverlapDays),
    );
    final start = overlapStart.isBefore(monthStart) ? overlapStart : monthStart;

    final knownSymbols = (await _db.getAllActiveStocks())
        .map((s) => s.symbol)
        .toSet();
    final errors = <String>[];
    var written = 0;
    var calls = 0;
    var pendingDetails = 0;

    if (_tpex != null && calls < maxCalls) {
      try {
        calls++;
        final rows = await _tpex.getExRightResults(
          startDate: start,
          endDate: end,
        );
        written += await _writeDistributions([
          for (final row in rows)
            if (knownSymbols.contains(row.symbol)) row,
        ]);
        await _recordListing(
          market: MarketCode.tpex,
          listed: rows,
          knownSymbols: knownSymbols,
          from: start,
          to: end,
          listedThrough: listedThrough,
          recordedAt: today,
          errors: errors,
        );
      } on RateLimitException {
        rethrow;
      } on NetworkException {
        rethrow;
      } catch (e) {
        AppLogger.warning('DividendSyncer', 'TPEX 除權除息同步失敗', e);
        errors.add('TPEX 除權除息: $e');
      }
    }

    if (_twse != null && calls < maxCalls) {
      try {
        calls++;
        final rows = await _twse.getExRightResults(
          startDate: start,
          endDate: end,
        );
        final known = [
          for (final row in rows)
            if (knownSymbols.contains(row.symbol)) row,
        ];
        written += await _writeDistributions([
          for (final row in known)
            if (!row.needsDetail) row,
        ]);
        await _db.updateDividendDistributionPrices([
          for (final row in known)
            if (row.needsDetail) dividendListedPrice(row),
        ]);

        final processed = await _db.getDividendDistributionKeys(
          from: start,
          to: end,
        );
        final pending = [
          for (final row in known)
            if (row.needsDetail &&
                !processed.contains((row.symbol, row.exDate)))
              row,
        ];
        final reasons = <(String, DateTime), DividendUnresolvedReason>{};
        try {
          for (final row in pending) {
            if (calls >= maxCalls) {
              pendingDetails++;
              continue;
            }
            await Future<void>.delayed(_detailCallDelay);
            calls++;
            final key = (row.symbol, row.exDate);
            try {
              final detail = await _twse.getExRightDetail(
                row.symbol,
                row.exDate,
              );
              if (!row.matchesReference(detail)) {
                reasons[key] = DividendUnresolvedReason.referenceMismatch;
                errors.add(
                  'TWSE 除權除息明細 ${row.symbol} '
                  '${_dateFormat.format(row.exDate)}: 明細推算的參考價與列表不符'
                  '（查到的可能是別次除權息）',
                );
                continue;
              }
              written += await _writeDistributions([row.withDetail(detail)]);
            } on RateLimitException {
              rethrow;
            } on NetworkException {
              rethrow;
            } catch (e) {
              reasons[key] = DividendUnresolvedReason.detailFailed;
              AppLogger.warning(
                'DividendSyncer',
                'TWSE 除權除息明細失敗: ${row.symbol}',
                e,
              );
              errors.add(
                'TWSE 除權除息明細 ${row.symbol} '
                '${_dateFormat.format(row.exDate)}: $e',
              );
            }
          }
        } finally {
          // 列表成功就記事實：明細被限流或斷線打斷也要記，未查的列以
          // pendingDetail 留在未解決清單；本身失敗只進 errors，不蓋過例外
          await _recordListing(
            market: MarketCode.twse,
            listed: rows,
            knownSymbols: knownSymbols,
            reasons: reasons,
            from: start,
            to: end,
            listedThrough: listedThrough,
            recordedAt: today,
            errors: errors,
          );
        }
      } on RateLimitException {
        rethrow;
      } on NetworkException {
        rethrow;
      } catch (e) {
        AppLogger.warning('DividendSyncer', 'TWSE 除權除息同步失敗', e);
        errors.add('TWSE 除權除息: $e');
      }
    }

    return DividendDistributionSyncResult(
      written: written,
      calls: calls,
      pendingDetails: pendingDetails,
      errors: errors,
    );
  }

  /// 寫入已拆開現金與配股的除權除息列，回傳筆數
  Future<int> _writeDistributions(List<ExRightResult> rows) async {
    await _db.upsertDividendDistributions([
      for (final row in rows) dividendDistributionCompanion(row),
    ]);
    return rows.length;
  }

  /// 記錄完整度事實；失敗只記 errors 與 warning，不往外拋（本月同步的
  /// 失敗一律進 errors，不中斷其他市場）
  Future<void> _recordListing({
    required String market,
    required List<ExRightResult> listed,
    required Set<String> knownSymbols,
    Map<(String, DateTime), DividendUnresolvedReason> reasons = const {},
    required DateTime from,
    required DateTime to,
    required DateTime listedThrough,
    required DateTime recordedAt,
    required List<String> errors,
  }) async {
    try {
      await _db.recordDividendListing(
        market: market,
        from: from,
        to: to,
        listedThrough: listedThrough,
        listedKnownKeys: {
          for (final r in listed)
            if (knownSymbols.contains(r.symbol)) (r.symbol, r.exDate),
        },
        notInMasterKeys: {
          for (final r in listed)
            if (!knownSymbols.contains(r.symbol)) (r.symbol, r.exDate),
        },
        reasons: reasons,
        recordedAt: recordedAt,
      );
    } catch (e) {
      AppLogger.warning('DividendSyncer', '$market 除權除息完整度紀錄失敗', e);
      errors.add('$market 除權除息完整度紀錄: $e');
    }
  }

  /// 建立股東會事件描述
  String? _buildMeetingDescription(TpexShareholderMeeting meeting) {
    final parts = <String>[];
    if (meeting.location != null) parts.add(meeting.location!);
    if (meeting.hasBoardElection) parts.add('改選董監事');
    if (meeting.hasEVoting) parts.add('電子投票');
    return parts.isEmpty ? null : parts.join(' | ');
  }

  /// 去重：同一 symbol + 同一日期 + 同一 eventType 只保留一筆
  List<StockEventCompanion> _deduplicateEvents(
    List<StockEventCompanion> companions,
  ) {
    final seen = <String>{};
    final result = <StockEventCompanion>[];
    for (final c in companions) {
      final sym = c.symbol.value ?? '';
      final date = c.eventDate.value;
      final type = c.eventType.value;
      // 月/日補零(2026-07-29 fix):未補零時 2026-1-12 與 2026-11-2 同為
      // '2026112',不同日期的常會/臨時會互撞、後者被靜默丟棄
      final mm = date.month.toString().padLeft(2, '0');
      final dd = date.day.toString().padLeft(2, '0');
      final key = '${sym}_${date.year}$mm${dd}_$type';
      if (seen.add(key)) {
        result.add(c);
      }
    }
    return result;
  }
}

/// 股東會同步結果
class ShareholderMeetingSyncResult {
  const ShareholderMeetingSyncResult({
    this.meetingEventsCreated = 0,
    this.errors = const [],
  });

  final int meetingEventsCreated;
  final List<String> errors;

  bool get hasErrors => errors.isNotEmpty;
}

/// 除權除息同步結果
class DividendDistributionSyncResult {
  const DividendDistributionSyncResult({
    required this.written,
    required this.calls,
    required this.pendingDetails,
    required this.errors,
  });

  /// 寫入列數（含金額皆 0 的已處理列）
  final int written;

  /// 列表＋明細呼叫次數
  final int calls;

  /// 超過每輪上限、留待下一輪的明細筆數
  final int pendingDetails;

  final List<String> errors;
}
