import 'package:drift/drift.dart';
import 'package:intl/intl.dart';

import 'package:daredevil/core/constants/api_config.dart';
import 'package:daredevil/core/exceptions/app_exception.dart';
import 'package:daredevil/core/utils/date_context.dart';
import 'package:daredevil/core/utils/logger.dart';
import 'package:daredevil/data/database/app_database.dart';
import 'package:daredevil/data/remote/tpex_client.dart';
import 'package:daredevil/data/remote/twse_client.dart';

/// 已拆開現金與配股的除權除息列 → 股利配發表的寫入列（本月同步與歷史回補
/// 共用）。列表拆不出、尚未補明細的列（[ExRightResult.needsDetail]）不可傳入。
DividendDistributionCompanion dividendDistributionCompanion(
  ExRightResult row,
) => DividendDistributionCompanion.insert(
  symbol: row.symbol,
  exDate: row.exDate,
  cashDividend: row.cashDividend!,
  stockSharesPerThousand: row.stockSharesPerThousand!,
);

/// 已宣告股利 + 股東會 + 除權除息同步器
///
/// 從 TWSE/TPEX 取得：
/// 1. 已宣告股利 upsert 至 DividendHistory（更新 exDividendDate/exRightsDate）
/// 2. 股東會日程寫入 StockEvent（eventType = SHAREHOLDER_MEETING）
/// 3. 除權除息計算結果寫入 DividendDistribution（[syncDistributions]）
///
/// 3 只管本月；歷史月份由 `DividendBackfiller` 回補（同一步驟、本月同步之後）。
///
/// 1、2（[sync]）在 UpdateService._syncAuxiliaryData()（並行階段）呼叫，與
/// MarketIndexSyncer、TdccHoldingSyncer 同級；3 在更新步驟 6.6（上櫃候選補充
/// 之後、評分之前）依序執行。
class DividendSyncer {
  DividendSyncer({
    required AppDatabase database,
    TwseClient? twseClient,
    TpexClient? tpexClient,
    Duration detailCallDelay = const Duration(
      milliseconds: ApiConfig.dividendCallDelayMs,
    ),
  }) : _db = database,
       _twse = twseClient,
       _tpex = tpexClient,
       _detailCallDelay = detailCallDelay;

  final AppDatabase _db;
  final TwseClient? _twse;
  final TpexClient? _tpex;

  /// TWT49UDetail 呼叫間隔（測試傳 [Duration.zero]）
  final Duration _detailCallDelay;

  static final _dateFormat = DateFormat('yyyy-MM-dd');

  /// 同步已宣告股利 + 股東會日程
  ///
  /// 回傳同步結果，包含 upsert 筆數和事件數。
  /// 各資料來源獨立 try/catch，單一來源失敗不影響其他；股東會事件的全市場重建
  /// 僅在所有已嘗試來源皆成功時執行（見 Phase 4），避免部分失敗誤刪既有資料。
  Future<DividendSyncResult> sync() async {
    var dividendsUpserted = 0;
    var meetingEventsCreated = 0;
    final errors = <String>[];

    // 追蹤各股東會來源本輪是否失敗。Phase 4 的全市場刪除只有在「所有已嘗試的
    // 股東會來源皆成功」時才安全——否則 meetingCompanions 只含部分市場，
    // delete-then-rewrite 會清掉失敗來源上一輪正確寫入的事件且無法補回。
    var twseMeetingsFailed = false;
    var tpexMeetingsFailed = false;

    // 取得 DB 中所有已知股票（FK constraint — 過濾 1101B 等特別股）
    final knownStocks = await _db.getAllActiveStocks();
    final knownSymbols = knownStocks.map((s) => s.symbol).toSet();

    // ==================================================
    // Phase 1: 取得已宣告股利 → upsert DividendHistory
    // ==================================================
    final dividendCompanions = <DividendHistoryCompanion>[];
    final meetingCompanions = <StockEventCompanion>[];

    // 1a. TWSE 已宣告股利（上市）
    if (_twse != null) {
      try {
        final twseData = await _twse.getDeclaredDividends();
        for (final item in twseData) {
          if (!knownSymbols.contains(item.symbol)) continue;

          dividendCompanions.add(
            _toDividendCompanion(
              symbol: item.symbol,
              year: item.dividendYear,
              cashDividend: item.cashDividend,
              stockDividend: item.stockDividend,
              exDividendDate: item.exDividendDate,
              exRightsDate: item.exRightsDate,
            ),
          );

          // 從 TWSE 資料提取股東會日期（Feature 3）
          if (item.shareholderMeetingDate != null) {
            meetingCompanions.add(
              StockEventCompanion.insert(
                symbol: Value(item.symbol),
                eventType: 'SHAREHOLDER_MEETING',
                eventDate: item.shareholderMeetingDate!,
                title: '${item.symbol} ${item.companyName} 股東會',
                description: const Value(null),
                isAutoGenerated: const Value(true),
              ),
            );
          }
        }
        AppLogger.info('DividendSyncer', 'TWSE 已宣告股利: ${twseData.length} 筆');
      } on RateLimitException {
        rethrow;
      } on NetworkException {
        rethrow;
      } catch (e) {
        // TWSE 股東會日期內嵌於已宣告股利回應中——此處失敗代表本輪 TWSE
        // （上市）股東會資料不完整，標記以阻擋 Phase 4 的全市場刪除。
        twseMeetingsFailed = true;
        AppLogger.warning('DividendSyncer', 'TWSE 已宣告股利同步失敗', e);
        errors.add('TWSE 已宣告股利: $e');
      }
    }

    // 1b. TPEX 已宣告股利（上櫃）
    if (_tpex != null) {
      try {
        final tpexData = await _tpex.getDeclaredDividends();
        for (final item in tpexData) {
          if (!knownSymbols.contains(item.symbol)) continue;

          dividendCompanions.add(
            _toDividendCompanion(
              symbol: item.symbol,
              year: item.dividendYear,
              cashDividend: item.cashDividend,
              stockDividend: item.stockDividend,
              exDividendDate: item.exDividendDate,
              exRightsDate: item.exRightsDate,
            ),
          );
        }
        AppLogger.info('DividendSyncer', 'TPEX 已宣告股利: ${tpexData.length} 筆');
      } on RateLimitException {
        rethrow;
      } on NetworkException {
        rethrow;
      } catch (e) {
        AppLogger.warning('DividendSyncer', 'TPEX 已宣告股利同步失敗', e);
        errors.add('TPEX 已宣告股利: $e');
      }
    }

    // ==================================================
    // Phase 2: Upsert DividendHistory
    // ==================================================
    if (dividendCompanions.isNotEmpty) {
      try {
        await _db.insertDividendData(dividendCompanions);
        dividendsUpserted = dividendCompanions.length;
        AppLogger.info('DividendSyncer', '股利資料 upsert: $dividendsUpserted 筆');
      } catch (e) {
        AppLogger.warning('DividendSyncer', '股利資料寫入失敗', e);
        errors.add('DB 寫入: $e');
      }
    }

    // ==================================================
    // Phase 3: 取得股東會日程（TPEX ap41_O）
    // ==================================================
    if (_tpex != null) {
      try {
        final meetings = await _tpex.getShareholderMeetings();
        for (final meeting in meetings) {
          if (!knownSymbols.contains(meeting.symbol)) continue;

          meetingCompanions.add(
            StockEventCompanion.insert(
              symbol: Value(meeting.symbol),
              eventType: 'SHAREHOLDER_MEETING',
              eventDate: meeting.meetingDate,
              title:
                  '${meeting.symbol} ${meeting.companyName} ${meeting.meetingType}',
              description: Value(_buildMeetingDescription(meeting)),
              isAutoGenerated: const Value(true),
            ),
          );
        }
        AppLogger.info('DividendSyncer', 'TPEX 股東會: ${meetings.length} 筆');
      } on RateLimitException {
        rethrow;
      } on NetworkException {
        rethrow;
      } catch (e) {
        tpexMeetingsFailed = true;
        AppLogger.warning('DividendSyncer', 'TPEX 股東會同步失敗', e);
        errors.add('TPEX 股東會: $e');
      }
    }

    // ==================================================
    // Phase 4: 寫入股東會 StockEvent（去重後）
    // ==================================================
    // deleteAutoGeneratedEventsByTypes 是全市場（不分 symbol/來源）刪除，故
    // 只有在所有已嘗試的股東會來源本輪皆成功時才可 delete-then-rewrite。若任一
    // 來源失敗，meetingCompanions 僅含成功來源的部分市場，此時重建會連同失敗
    // 來源上一輪正確寫入的事件一併清空且無法補回——改為略過本輪重建、保留既有
    // 事件，待下輪所有來源皆成功再重建。
    final meetingSourceFailed = twseMeetingsFailed || tpexMeetingsFailed;
    if (meetingCompanions.isNotEmpty && meetingSourceFailed) {
      AppLogger.warning('DividendSyncer', '部分股東會來源失敗，略過重建以保留既有事件');
      errors.add('股東會事件: 部分來源失敗，略過重建以保留既有資料');
    } else if (meetingCompanions.isNotEmpty) {
      try {
        // 去重：同一 symbol + 同一日期只保留一筆（TWSE 和 TPEX 可能重複）
        final uniqueMeetings = _deduplicateEvents(meetingCompanions);

        await _db.transaction(() async {
          // 只刪除 SHAREHOLDER_MEETING 類型的自動事件，不影響其他
          await _db.deleteAutoGeneratedEventsByTypes(const [
            'SHAREHOLDER_MEETING',
          ]);
          await _db.insertStockEvents(uniqueMeetings);
        });
        meetingEventsCreated = uniqueMeetings.length;
        AppLogger.info('DividendSyncer', '股東會事件寫入: $meetingEventsCreated 筆');
      } catch (e) {
        AppLogger.warning('DividendSyncer', '股東會事件寫入失敗', e);
        errors.add('股東會事件: $e');
      }
    }

    return DividendSyncResult(
      dividendsUpserted: dividendsUpserted,
      meetingEventsCreated: meetingEventsCreated,
      errors: errors,
    );
  }

  /// 同步本月的除權除息至股利配發表（dividend_distribution）
  ///
  /// 範圍＝本月初與今天往前 [ApiConfig.dividendSyncOverlapDays] 天中較早者，
  /// 至今天。先上櫃（1 次列表、不需明細），再上市（1 次列表）：「息」列
  /// 直接寫入；「權」「權息」列拆不開現金與配股，逐列查 TWT49UDetail——
  /// DB 已有該列（含只有現金增資、金額皆 0 的已處理列）就不再查。不在
  /// 股票主檔的代號在查明細之前略過（外鍵會讓整批寫入失敗）。
  ///
  /// 列表與明細合計最多 [maxCalls] 次，沒查到的明細留待下一輪
  /// （[DividendDistributionSyncResult.pendingDetails]）。每筆明細查到就
  /// 立刻寫入：中途被限流或斷線打斷，已查的不會丟。每次查明細前等
  /// [_detailCallDelay]。
  ///
  /// 一般失敗（列表不可信、單列明細不可信）記進 errors 後繼續；
  /// [RateLimitException]／[NetworkException] 往上拋——前者由 UpdateService
  /// 中止本輪，後者記錯誤後續跑。
  Future<DividendDistributionSyncResult> syncDistributions({
    required DateTime today,
    required int maxCalls,
  }) async {
    final end = DateContext.normalize(today);
    final monthStart = DateTime(end.year, end.month);
    final overlapStart = end.subtract(
      const Duration(days: ApiConfig.dividendSyncOverlapDays),
    );
    final start = overlapStart.isBefore(monthStart) ? overlapStart : monthStart;

    final knownSymbols = (await _db.getAllActiveStocks())
        .map((s) => s.symbol)
        .toSet();
    final errors = <String>[];
    var written = 0;
    var calls = 0;
    var pendingDetails = 0;

    if (_tpex != null && calls < maxCalls) {
      try {
        calls++;
        final rows = await _tpex.getExRightResults(
          startDate: start,
          endDate: end,
        );
        written += await _writeDistributions([
          for (final row in rows)
            if (knownSymbols.contains(row.symbol)) row,
        ]);
      } on RateLimitException {
        rethrow;
      } on NetworkException {
        rethrow;
      } catch (e) {
        AppLogger.warning('DividendSyncer', 'TPEX 除權除息同步失敗', e);
        errors.add('TPEX 除權除息: $e');
      }
    }

    if (_twse != null && calls < maxCalls) {
      try {
        calls++;
        final rows = await _twse.getExRightResults(
          startDate: start,
          endDate: end,
        );
        final known = [
          for (final row in rows)
            if (knownSymbols.contains(row.symbol)) row,
        ];
        written += await _writeDistributions([
          for (final row in known)
            if (!row.needsDetail) row,
        ]);

        final processed = await _db.getDividendDistributionKeys(
          from: start,
          to: end,
        );
        final pending = [
          for (final row in known)
            if (row.needsDetail &&
                !processed.contains((row.symbol, row.exDate)))
              row,
        ];
        for (final row in pending) {
          if (calls >= maxCalls) {
            pendingDetails++;
            continue;
          }
          await Future<void>.delayed(_detailCallDelay);
          calls++;
          try {
            final detail = await _twse.getExRightDetail(row.symbol, row.exDate);
            if (!row.matchesReference(detail)) {
              errors.add(
                'TWSE 除權除息明細 ${row.symbol} '
                '${_dateFormat.format(row.exDate)}: 明細推算的參考價與列表不符'
                '（查到的可能是別次除權息）',
              );
              continue;
            }
            written += await _writeDistributions([row.withDetail(detail)]);
          } on RateLimitException {
            rethrow;
          } on NetworkException {
            rethrow;
          } catch (e) {
            AppLogger.warning(
              'DividendSyncer',
              'TWSE 除權除息明細失敗: ${row.symbol}',
              e,
            );
            errors.add(
              'TWSE 除權除息明細 ${row.symbol} '
              '${_dateFormat.format(row.exDate)}: $e',
            );
          }
        }
      } on RateLimitException {
        rethrow;
      } on NetworkException {
        rethrow;
      } catch (e) {
        AppLogger.warning('DividendSyncer', 'TWSE 除權除息同步失敗', e);
        errors.add('TWSE 除權除息: $e');
      }
    }

    return DividendDistributionSyncResult(
      written: written,
      calls: calls,
      pendingDetails: pendingDetails,
      errors: errors,
    );
  }

  /// 寫入已拆開現金與配股的除權除息列，回傳筆數
  Future<int> _writeDistributions(List<ExRightResult> rows) async {
    await _db.upsertDividendDistributions([
      for (final row in rows) dividendDistributionCompanion(row),
    ]);
    return rows.length;
  }

  /// 建立 DividendHistoryCompanion
  DividendHistoryCompanion _toDividendCompanion({
    required String symbol,
    required int year,
    required double cashDividend,
    required double stockDividend,
    DateTime? exDividendDate,
    DateTime? exRightsDate,
  }) {
    return DividendHistoryCompanion(
      symbol: Value(symbol),
      year: Value(year),
      cashDividend: Value(cashDividend),
      stockDividend: Value(stockDividend),
      exDividendDate: Value(
        exDividendDate != null ? _dateFormat.format(exDividendDate) : null,
      ),
      exRightsDate: Value(
        exRightsDate != null ? _dateFormat.format(exRightsDate) : null,
      ),
    );
  }

  /// 建立股東會事件描述
  String? _buildMeetingDescription(TpexShareholderMeeting meeting) {
    final parts = <String>[];
    if (meeting.location != null) parts.add(meeting.location!);
    if (meeting.hasBoardElection) parts.add('改選董監事');
    if (meeting.hasEVoting) parts.add('電子投票');
    return parts.isEmpty ? null : parts.join(' | ');
  }

  /// 去重：同一 symbol + 同一日期 + 同一 eventType 只保留一筆
  List<StockEventCompanion> _deduplicateEvents(
    List<StockEventCompanion> companions,
  ) {
    final seen = <String>{};
    final result = <StockEventCompanion>[];
    for (final c in companions) {
      final sym = c.symbol.value ?? '';
      final date = c.eventDate.value;
      final type = c.eventType.value;
      // 月/日補零(2026-07-29 fix):未補零時 2026-1-12 與 2026-11-2 同為
      // '2026112',不同日期的常會/臨時會互撞、後者被靜默丟棄
      final mm = date.month.toString().padLeft(2, '0');
      final dd = date.day.toString().padLeft(2, '0');
      final key = '${sym}_${date.year}$mm${dd}_$type';
      if (seen.add(key)) {
        result.add(c);
      }
    }
    return result;
  }
}

/// 股利同步結果
class DividendSyncResult {
  const DividendSyncResult({
    this.dividendsUpserted = 0,
    this.meetingEventsCreated = 0,
    this.errors = const [],
  });

  final int dividendsUpserted;
  final int meetingEventsCreated;
  final List<String> errors;

  bool get hasErrors => errors.isNotEmpty;
}

/// 除權除息同步結果
class DividendDistributionSyncResult {
  const DividendDistributionSyncResult({
    required this.written,
    required this.calls,
    required this.pendingDetails,
    required this.errors,
  });

  /// 寫入列數（含金額皆 0 的已處理列）
  final int written;

  /// 列表＋明細呼叫次數
  final int calls;

  /// 超過每輪上限、留待下一輪的明細筆數
  final int pendingDetails;

  final List<String> errors;
}
