import 'package:drift/drift.dart';
import 'package:intl/intl.dart';

import 'package:daredevil/core/utils/logger.dart';
import 'package:daredevil/data/database/app_database.dart';
import 'package:daredevil/data/remote/tpex_client.dart';
import 'package:daredevil/data/remote/twse_client.dart';

/// 事件日曆 Repository
///
/// 管理行事曆事件，包括使用者自訂事件與系統自動產生的除權息事件。
class EventRepository {
  EventRepository({
    required AppDatabase database,
    TwseClient? twseClient,
    TpexClient? tpexClient,
  }) : _db = database,
       _twseClient = twseClient,
       _tpexClient = tpexClient;

  final AppDatabase _db;

  /// 停券預告＋除權息預告（上市側）；null 時對應同步直接回 0（測試便利）
  final TwseClient? _twseClient;

  /// 除權息預告（上櫃側）；null 時 [syncDividendEvents] 直接回 0
  final TpexClient? _tpexClient;

  static final _dateFormat = DateFormat('yyyy-MM-dd');

  // ==================================================
  // 事件查詢
  // ==================================================

  /// 取得指定日期範圍內的事件
  Future<List<StockEventEntry>> getEventsInRange(
    DateTime start,
    DateTime end, {
    List<String>? symbols,
  }) {
    return _db.getEventsInRange(start, end, symbols: symbols);
  }

  // ==================================================
  // 事件操作
  // ==================================================

  /// 新增自訂事件
  Future<int> addCustomEvent({
    String? symbol,
    required DateTime eventDate,
    required String title,
    String? description,
  }) {
    return _db.insertStockEvent(
      StockEventCompanion.insert(
        symbol: Value(symbol),
        eventType: 'CUSTOM',
        eventDate: eventDate,
        title: title,
        description: Value(description),
      ),
    );
  }

  /// 更新自訂事件
  Future<void> updateCustomEvent({
    required int id,
    String? symbol,
    required DateTime eventDate,
    required String title,
    String? description,
  }) {
    return _db.updateStockEvent(
      id,
      StockEventCompanion(
        symbol: Value(symbol),
        eventDate: Value(eventDate),
        title: Value(title),
        description: Value(description),
      ),
    );
  }

  /// 刪除事件
  Future<void> deleteEvent(int id) {
    return _db.deleteStockEvent(id);
  }

  // ==================================================
  // 除權息日同步
  // ==================================================

  /// 從 TWSE/TPEx 除權除息預告表同步除權息事件（2026-08-01 換源重寫）。
  ///
  /// 原實作讀舊股利表（2026-10 已移除）的日期欄——但大宗「已宣告股利」同步只帶
  /// 金額不帶日期（實測 3,495 筆僅 6 筆有日期，功能自上線即空轉），且該表
  /// 主鍵 (symbol, year) 裝不下季配息一年多個除息日。改由官方預告表
  /// （TWT48U_ALL / tpex_exright_prepost，免額度、帶確定交易日）直接建事件。
  ///
  /// - **全市場不篩自選**（與處置出關同模式）：預告表本身即全市場且量小
  ///   （~240 筆），scoping 由行事曆篩選器負責
  /// - **delete-by-type + rebuild**：預告表是權威現況，公司改期整批自癒
  ///   （法說會累積式的更正殘留問題在此天生不存在）
  /// - **兩市場 both-or-nothing**：任一側抓取失敗直接拋出、不進刪除交易
  ///   ——部分重建會把另一市場上一輪的事件誤刪且補不回
  /// - 任一 client 未注入（測試便利）回零、不動既有事件
  /// - 預告代碼含 ETF/特別股（如 00400A）——`stock_master` 有 FK，
  ///   不在主檔者跳過
  Future<({int exDividend, int exRights, int total})>
  syncDividendEvents() async {
    final twse = _twseClient;
    final tpex = _tpexClient;
    if (twse == null || tpex == null) {
      return (exDividend: 0, exRights: 0, total: 0);
    }

    final rows = [
      ...await twse.getExRightPreannouncements(),
      ...await tpex.getExRightPreannouncements(),
    ];

    final knownStocks = await _db.getAllActiveStocks();
    final knownSymbols = knownStocks.map((s) => s.symbol).toSet();

    final companions = <StockEventCompanion>[];
    for (final row in rows) {
      if (!knownSymbols.contains(row.symbol)) continue;

      if (row.hasDividend) {
        final cash = row.cashDividend;
        companions.add(
          StockEventCompanion.insert(
            symbol: Value(row.symbol),
            eventType: 'EX_DIVIDEND',
            eventDate: row.date,
            title: '${row.symbol} 除息',
            description: Value(
              cash == null ? '除息' : '現金股利 ${cash.toStringAsFixed(2)} 元',
            ),
            isAutoGenerated: const Value(true),
          ),
        );
      }

      if (row.hasRights) {
        final ratio = row.stockDividendRatio;
        companions.add(
          StockEventCompanion.insert(
            symbol: Value(row.symbol),
            eventType: 'EX_RIGHTS',
            eventDate: row.date,
            title: '${row.symbol} 除權',
            description: Value(
              ratio == null ? '除權' : '配股率 ${ratio.toStringAsFixed(2)}',
            ),
            isAutoGenerated: const Value(true),
          ),
        );
      }
    }

    // 單一交易中刪除舊的除權息事件並批次插入新事件
    // 只刪 EX_DIVIDEND + EX_RIGHTS，不影響 SHAREHOLDER_MEETING 等其他自動事件
    await _db.transaction(() async {
      await _db.deleteAutoGeneratedEventsByTypes(const [
        'EX_DIVIDEND',
        'EX_RIGHTS',
      ]);
      await _db.insertStockEvents(companions);
    });

    final exDividendCount = companions
        .where((c) => c.eventType.value == 'EX_DIVIDEND')
        .length;
    final exRightsCount = companions
        .where((c) => c.eventType.value == 'EX_RIGHTS')
        .length;
    AppLogger.info(
      'EventRepo',
      '除權息事件重建: 除息 $exDividendCount、除權 $exRightsCount',
    );
    return (
      exDividend: exDividendCount,
      exRights: exRightsCount,
      total: companions.length,
    );
  }

  // ==================================================
  // 處置出關日同步
  // ==================================================

  /// 從 active DISPOSAL 警示產生「處置出關」事件。
  ///
  /// v3 交易系統把處置股踢出可交易宇宙，出關日＝重新可交易的日子；
  /// 事件日取 `disposal_end_date`（處置最後一日），標題註明次日恢復。
  /// 與除權息同步同模式：delete-by-type 後重建，冪等。
  Future<int> syncDisposalEndEvents() async {
    final disposals = await _db.getActiveWarningsByType('DISPOSAL');
    final companions = <StockEventCompanion>[];
    for (final w in disposals) {
      final end = w.disposalEndDate;
      if (end == null) continue;
      companions.add(
        StockEventCompanion.insert(
          symbol: Value(w.symbol),
          eventType: 'DISPOSAL_END',
          eventDate: end,
          title: '${w.symbol} 處置結束',
          description: const Value('處置期滿，次一交易日恢復一般交易'),
          isAutoGenerated: const Value(true),
        ),
      );
    }

    await _db.transaction(() async {
      await _db.deleteAutoGeneratedEventsByTypes(const ['DISPOSAL_END']);
      await _db.insertStockEvents(companions);
    });
    return companions.length;
  }

  // ==================================================
  // 停券預告同步
  // ==================================================

  /// 從 TWSE 停資停券預告（BFI84U）產生自選/持倉股的停券事件。
  ///
  /// 停券起日前的回補賣壓與軋空是短線催化劑；事件日取停券起日，
  /// 描述帶原因與迄日。與其他自動事件同模式：delete-by-type 後重建。
  Future<int> syncShortSuspensionEvents() async {
    final client = _twseClient;
    if (client == null) return 0;

    final watchlistEntries = await _db.getWatchlist();
    final portfolioPositions = await _db.getPortfolioPositions();
    final symbols = <String>{
      ...watchlistEntries.map((e) => e.symbol),
      ...portfolioPositions.map((e) => e.symbol),
    };

    final rows = await client.getShortSellingSuspensions();
    final companions = <StockEventCompanion>[];
    for (final row in rows) {
      if (!symbols.contains(row.code)) continue;
      final start = rocDateToDateTime(row.startDate);
      if (start == null) continue;
      final end = rocDateToDateTime(row.endDate);
      final endText = end == null ? '' : '，至 ${_dateFormat.format(end)} 恢復';
      companions.add(
        StockEventCompanion.insert(
          symbol: Value(row.code),
          eventType: 'SHORT_SUSPENSION',
          eventDate: start,
          title: '${row.code} 停券起始',
          description: Value('原因：${row.reason}$endText'),
          isAutoGenerated: const Value(true),
        ),
      );
    }

    await _db.transaction(() async {
      await _db.deleteAutoGeneratedEventsByTypes(const ['SHORT_SUSPENSION']);
      await _db.insertStockEvents(companions);
    });
    return companions.length;
  }

  // ==================================================
  // 法說會同步（自重大訊息公告抽取）
  // ==================================================

  /// 從**已存重大訊息公告**抽自選∪持倉股的法說會，寫入 EARNINGS 自動事件。
  ///
  /// **不重打 API**：t187ap04_L 是單日檔（只含前一營業日公告），過窗即失；
  /// 公告已由 news 同步永久存進 news_item，故此處讀 [getMaterialAnnouncements]
  /// 累積資料解析，哪天按同步都抓得回過去的法說會（2026-07-24 修：原靠重打
  /// API＝1 天窗，錯過就永遠建不出事件）。
  ///
  /// 事件日＝公告內結構化欄位的**開會日**。**累積式**寫入（先比對既有
  /// 事件的 (symbol, 日) 去重），不可 delete-by-type 重建（會抹掉往日累積）。
  ///
  /// ⚠️ 若未來新增「財報公布」等第二個 EARNINGS producer：本方法的
  /// (symbol, 日) 去重會讀到**兩個 producer 的事件互相壓制**——屆時需以
  /// title/來源子欄位區分，並考慮 prune 已過期的 auto EARNINGS。
  ///
  /// ⚠️ 已知限制（2026-08-01 複審列管）：公告**更正/改期**會派生第二筆
  /// 事件且舊日期事件永久殘留——(symbol, 日) key 只防重跑冪等，不防同一
  /// 場次的日期修正；公告永久累積代表舊公告永遠派生舊日期，手動刪事件
  /// 也會被下次同步復活。盲目 supersede 會誤殺同公司多場法說會的合法
  /// 情境（真 DB 測試鎖此分支），正確的更正語意需真實 MOPS 更正公告
  /// 樣本才能設計——樣本到手前不做啟發式。
  Future<int> syncInvestorConferenceEvents() async {
    final watchlistEntries = await _db.getWatchlist();
    final portfolioPositions = await _db.getPortfolioPositions();
    final symbols = <String>{
      ...watchlistEntries.map((e) => e.symbol),
      ...portfolioPositions.map((e) => e.symbol),
    };
    if (symbols.isEmpty) return 0;

    final announcements = await _db.getMaterialAnnouncements();
    final existing = await _db.getAutoGeneratedEventsByType('EARNINGS');
    final existingKeys = {
      for (final e in existing)
        '${e.symbol}_${e.eventDate.year}-${e.eventDate.month}-${e.eventDate.day}',
    };

    // 收集後單一交易批寫(2026-08-01 Tier 1:原為迴圈內逐筆 insert 且
    // 無交易——5 個 producer 中唯一者,中途失敗會留半批)
    final companions = <StockEventCompanion>[];
    for (final a in announcements) {
      if (!symbols.contains(a.symbol)) continue;
      final date = investorConferenceDate(a.text);
      if (date == null) continue;
      final key = '${a.symbol}_${date.year}-${date.month}-${date.day}';
      if (existingKeys.contains(key)) continue;
      existingKeys.add(key);
      companions.add(
        StockEventCompanion.insert(
          symbol: Value(a.symbol),
          eventType: 'EARNINGS',
          eventDate: date,
          title: '${a.symbol} 法說會',
          isAutoGenerated: const Value(true),
        ),
      );
    }
    if (companions.isNotEmpty) {
      await _db.transaction(() async {
        await _db.insertStockEvents(companions);
      });
    }
    return companions.length;
  }
}
