import 'package:easy_localization/easy_localization.dart' show DateFormat;
import 'package:flutter/gestures.dart' show PointerDeviceKind;
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:table_calendar/table_calendar.dart';

import 'package:daredevil/data/database/app_database.dart';
import 'package:daredevil/presentation/providers/event_calendar_provider.dart';
import 'package:daredevil/presentation/screens/calendar/event_calendar_screen.dart';

import '../../../helpers/provider_test_helpers.dart';
import '../../../helpers/widget_test_helpers.dart';

// ==========================================
// Fake Notifier
// ==========================================

FakeEventCalendarNotifier? lastFakeNotifier;

class FakeEventCalendarNotifier extends EventCalendarNotifier {
  EventCalendarState initialState = EventCalendarState();
  final toggled = <EventType>[];
  final filters = <CalendarFilter>[];

  @override
  EventCalendarState build() => initialState;

  @override
  Future<void> init() async {}

  @override
  Future<bool> loadMonthEvents(DateTime month) async => true;

  @override
  void selectDate(DateTime date) {}

  @override
  Future<void> setFilter(CalendarFilter filter) async {
    filters.add(filter);
  }

  @override
  Future<void> addEvent({
    String? symbol,
    required DateTime eventDate,
    required String title,
    String? description,
  }) async {}

  @override
  Future<void> deleteEvent(int id) async {}

  @override
  Future<
    ({int exDividend, int exRights, int total, List<String> failedSources})
  >
  syncDividendEvents() async =>
      (exDividend: 0, exRights: 0, total: 0, failedSources: const <String>[]);

  @override
  void toggleEventType(EventType type) {
    toggled.add(type);
  }
}

// ==========================================
// Tests
// ==========================================

void main() {
  setUpAll(() async {
    await setupTestLocalization();
  });

  void widenViewport(WidgetTester tester) {
    tester.view.physicalSize = const Size(5000, 8000);
    addTearDown(() => tester.view.resetPhysicalSize());
  }

  Widget buildTestWidget({
    EventCalendarState? calendarState,
    Brightness brightness = Brightness.light,
    DateTime? focusedDay,
  }) {
    return buildProviderTestApp(
      EventCalendarScreen(initialFocusedDay: focusedDay),
      overrides: [
        eventCalendarProvider.overrideWith(() {
          final n = FakeEventCalendarNotifier();
          n.initialState = calendarState ?? EventCalendarState();
          lastFakeNotifier = n;
          return n;
        }),
      ],
      brightness: brightness,
    );
  }

  StockEventEntry createEvent({
    int id = 1,
    required String symbol,
    String eventType = 'EX_DIVIDEND',
    String title = 'Test Event',
    String? description,
    DateTime? eventDate,
  }) {
    return StockEventEntry(
      id: id,
      symbol: symbol,
      eventDate: eventDate ?? DateTime(2026, 2, 20),
      eventType: eventType,
      title: title,
      description: description,
      isAutoGenerated: false,
      createdAt: DateTime(2026, 2, 1),
    );
  }

  group('EventCalendarScreen', () {
    testWidgets('shows AppBar with title', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      expect(find.byType(AppBar), findsOneWidget);
    });

    testWidgets('shows filter icon', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      expect(find.byIcon(Icons.filter_list), findsOneWidget);
    });

    testWidgets('shows loading indicator', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(
        buildTestWidget(calendarState: EventCalendarState(isLoading: true)),
      );
      await tester.pump(const Duration(seconds: 1));

      expect(find.byType(CircularProgressIndicator), findsOneWidget);
    });

    testWidgets('shows empty state when no events for selected day', (
      tester,
    ) async {
      widenViewport(tester);
      await tester.pumpWidget(
        buildTestWidget(
          calendarState: EventCalendarState(
            selectedDate: DateTime(2026, 2, 20),
          ),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      expect(find.byIcon(Icons.event_busy), findsOneWidget);
    });

    testWidgets('shows events for selected day', (tester) async {
      widenViewport(tester);
      final events = [
        createEvent(id: 1, symbol: '2330', title: 'TSMC Dividend'),
        createEvent(
          id: 2,
          symbol: '2317',
          eventType: 'EARNINGS',
          title: 'Hon Hai Earnings',
        ),
      ];
      await tester.pumpWidget(
        buildTestWidget(
          calendarState: EventCalendarState(
            selectedDate: DateTime(2026, 2, 20),
            selectedDayEvents: events,
          ),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      expect(find.text('TSMC Dividend'), findsOneWidget);
      expect(find.text('Hon Hai Earnings'), findsOneWidget);
    });

    testWidgets('shows FAB for adding event', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      expect(find.byType(FloatingActionButton), findsOneWidget);
      expect(find.byIcon(Icons.add), findsOneWidget);
    });

    testWidgets('shows sync icon', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      expect(find.byIcon(Icons.sync), findsOneWidget);
    });

    testWidgets('format button uses localized labels instead of package '
        'English defaults', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      // 套件預設 availableCalendarFormats 是英文（'2 weeks' 等）；本 app 需
      // 傳入 i18n key（測試環境 .tr() 回傳 key 本身）。formatButtonShowsNext
      // 預設 true → 月檢視下按鈕顯示「下一個」格式（twoWeeks）的 label。
      expect(find.text('2 weeks'), findsNothing);
      expect(find.text('calendar.formatTwoWeeks'), findsOneWidget);
    });

    testWidgets('wide viewport: two panes fill window width adaptively', (
      tester,
    ) async {
      widenViewport(tester); // 5000x8000 physical / dpr 3 ≈ 1666 邏輯寬
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      // 自適應：雙欄吃滿視窗（僅留 16dp 外框），不得置中留大幅死空白
      // （2026-07-24 使用者回饋：左右兩側空白很大）
      final calendarLeft = tester
          .getTopLeft(find.byType(TableCalendar<StockEventEntry>))
          .dx;
      expect(
        calendarLeft,
        lessThan(100),
        reason: '左欄應貼近視窗左緣（外框 padding 內），非置中留白',
      );
    });

    testWidgets('wide viewport uses two-pane layout (calendar left, '
        'upcoming+day events right)', (tester) async {
      widenViewport(tester); // 邏輯寬 ~1666 ≥ Breakpoints.tablet → 雙欄
      await tester.pumpWidget(
        buildTestWidget(
          calendarState: EventCalendarState(
            selectedDate: DateTime(2026, 2, 20),
            upcomingEvents: [createEvent(id: 9, symbol: '2330')],
          ),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      final calendarRight = tester
          .getBottomRight(find.byType(TableCalendar<StockEventEntry>))
          .dx;
      final upcomingLeft = tester
          .getTopLeft(find.text('calendar.upcomingTitle'))
          .dx;
      expect(
        upcomingLeft,
        greaterThan(calendarRight),
        reason: '寬視窗下「未來14天」應在月曆右側欄，而非上方',
      );
    });

    testWidgets('narrow viewport keeps single-column layout '
        '(upcoming above calendar)', (tester) async {
      // 邏輯 560x800（<1024 仍屬單欄）。不用 400：測試環境 .tr() 會把
      // 'calendar.formatTwoWeeks' key 原樣渲染進 format 按鈕，400 寬會被
      // 長 key 撐爆 header Row（僅測試 artifact，真翻譯為「兩週」）。
      tester.view.physicalSize = const Size(1680, 2400);
      addTearDown(() => tester.view.resetPhysicalSize());
      await tester.pumpWidget(
        buildTestWidget(
          calendarState: EventCalendarState(
            upcomingEvents: [createEvent(id: 9, symbol: '2330')],
          ),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      final upcomingBottom = tester
          .getBottomLeft(find.text('calendar.upcomingTitle'))
          .dy;
      final calendarTop = tester
          .getTopLeft(find.byType(TableCalendar<StockEventEntry>))
          .dy;
      expect(
        upcomingBottom,
        lessThan(calendarTop),
        reason: '窄視窗維持單欄：「未來14天」在月曆上方',
      );
    });

    testWidgets('filter chips: 兩態皆中性、類型色只留色點 avatar', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(
        buildTestWidget(
          calendarState: EventCalendarState(
            selectedEventTypes: EventType.values.toSet()
              ..remove(EventType.exDividend),
          ),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      final chips = tester
          .widgetList<FilterChip>(find.byType(FilterChip))
          .toList();
      expect(chips, hasLength(EventType.values.length));

      // 預設五類全選會恆常呈彩虹，故兩態 label 皆不得著類型色、
      // avatar 一律為小色點（識別靠色點、選取靠底色＋勾勾）
      for (final chip in chips) {
        expect(
          chip.labelStyle?.color,
          isNull,
          reason: 'chip label 不著類型色（選中與否皆同）',
        );
        expect(
          chip.avatar,
          isNot(isA<Icon>()),
          reason: 'avatar 一律為色點而非彩色 icon',
        );
      }
      expect(
        chips.where((c) => !c.selected),
        hasLength(1),
        reason: 'exDividend 應為唯一未選中',
      );
    });

    testWidgets('wide viewport uses taller calendar rows', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));
      final wide = tester.widget<TableCalendar<StockEventEntry>>(
        find.byType(TableCalendar<StockEventEntry>),
      );
      // 高視窗（邏輯 2666 高）以當月實際週數動態撐滿 → 觸頂 176
      // （128 在 2560 級大視窗會剩 ~400dp 黑底，2026-07-24 使用者回饋）
      expect(wide.rowHeight, 176, reason: '高視窗月曆格高應動態撐滿至上限');

      tester.view.physicalSize = const Size(1680, 2400); // 邏輯 560 → 單欄
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));
      final narrow = tester.widget<TableCalendar<StockEventEntry>>(
        find.byType(TableCalendar<StockEventEntry>),
      );
      expect(narrow.rowHeight, 52, reason: '窄視窗維持套件預設 52');
    });

    testWidgets('today button jumps focus back to current month', (
      tester,
    ) async {
      widenViewport(tester);
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      expect(find.byIcon(Icons.today), findsOneWidget);

      await tester.tap(find.byIcon(Icons.chevron_right)); // 翻到下個月
      await tester.pump(const Duration(seconds: 1));
      await tester.tap(find.byIcon(Icons.today));
      await tester.pump(const Duration(seconds: 1));

      final cal = tester.widget<TableCalendar<StockEventEntry>>(
        find.byType(TableCalendar<StockEventEntry>),
      );
      final now = DateTime.now();
      expect(
        (cal.focusedDay.year, cal.focusedDay.month),
        (now.year, now.month),
        reason: '按回今日應跳回當前月份',
      );
    });

    testWidgets('wide upcoming cards show description line', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(
        buildTestWidget(
          calendarState: EventCalendarState(
            upcomingEvents: [
              createEvent(id: 9, symbol: '2330', description: '現金股利 3.0 元'),
            ],
          ),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      expect(find.text('現金股利 3.0 元'), findsOneWidget, reason: '寬版直列卡應顯示描述行');
    });

    testWidgets('tapping header title opens date picker', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      final title = DateFormat.yMMMM().format(DateTime.now());
      await tester.tap(find.text(title));
      await tester.pumpAndSettle();

      expect(find.byType(DatePickerDialog), findsOneWidget);
    });

    testWidgets('wide month stats card counts types and toggles filter', (
      tester,
    ) async {
      widenViewport(tester);
      final now = DateTime.now();
      final d1 = DateTime(now.year, now.month, 10);
      final d2 = DateTime(now.year, now.month, 20);
      await tester.pumpWidget(
        buildTestWidget(
          calendarState: EventCalendarState(
            events: {
              d1: [createEvent(id: 1, symbol: '2330', eventDate: d1)],
              d2: [
                createEvent(
                  id: 2,
                  symbol: '2317',
                  eventType: 'SHAREHOLDER_MEETING',
                  eventDate: d2,
                ),
              ],
            },
          ),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      expect(find.text('calendar.monthStats'), findsOneWidget);
      final exDivRow = find.byKey(const ValueKey('monthStat_exDividend'));
      expect(exDivRow, findsOneWidget);

      // pills 橫排：前兩類 pill 應在同一列（Wrap，非整寬直列）
      final dy1 = tester.getTopLeft(exDivRow).dy;
      final dy2 = tester
          .getTopLeft(find.byKey(const ValueKey('monthStat_exRights')))
          .dy;
      expect(dy1, dy2, reason: '統計 pills 應橫向排列');

      // 零場次類型（earnings 本月 0）降透明度；有場次（exDividend 1）全亮
      double opacityOf(String name) => tester
          .widget<Opacity>(
            find
                .descendant(
                  of: find.byKey(ValueKey('monthStat_$name')),
                  matching: find.byType(Opacity),
                )
                .first,
          )
          .opacity;
      expect(opacityOf('earnings'), lessThan(1), reason: '0 場次應降透明');
      expect(opacityOf('exDividend'), 1.0);

      await tester.tap(exDivRow);
      await tester.pump();
      expect(
        lastFakeNotifier!.toggled,
        contains(EventType.exDividend),
        reason: '點統計 pill 應切換該類型篩選',
      );
    });

    testWidgets('horizontal upcoming strip is mouse-draggable', (tester) async {
      // 桌面單欄：Flutter 預設 dragDevices 不含 mouse，橫向卡列會拖不動
      tester.view.physicalSize = const Size(1680, 2400); // 邏輯 560 → 單欄
      addTearDown(() => tester.view.resetPhysicalSize());
      await tester.pumpWidget(
        buildTestWidget(
          calendarState: EventCalendarState(
            upcomingEvents: [createEvent(id: 9, symbol: '2330')],
          ),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      final config = tester.widget<ScrollConfiguration>(
        find
            .ancestor(
              of: find.byType(ListView),
              matching: find.byType(ScrollConfiguration),
            )
            .first,
      );
      expect(
        config.behavior.dragDevices,
        containsAll([PointerDeviceKind.mouse, PointerDeviceKind.trackpad]),
        reason: '橫向卡列須可用滑鼠/觸控板拖動',
      );
    });

    testWidgets('selected day circle keeps fixed size at tall rows', (
      tester,
    ) async {
      widenViewport(tester); // rowHeight 觸頂，圈不得跟著膨脹
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      final circle = find.byKey(const ValueKey('selectedDayCircle'));
      expect(circle, findsOneWidget);
      expect(
        tester.getSize(circle),
        const Size(44, 44),
        reason: '今日/選中圈固定 44dp，不隨格高等比放大成氣球',
      );
    });

    test('calendarWeekRows 按週一起算回實際週數', () {
      expect(calendarWeekRows(DateTime(2026, 7)), 5); // 7/1 週三
      expect(calendarWeekRows(DateTime(2026, 8)), 6); // 8/1 週六
      expect(calendarWeekRows(DateTime(2027, 2)), 4); // 2/1 週一、28 天
    });

    testWidgets('day list keeps bottom clearance for FAB', (tester) async {
      // 窄版 FAB 蓋住當日清單最後一張卡右下角（2026-07-24 使用者回饋）
      tester.view.physicalSize = const Size(1680, 2400);
      addTearDown(() => tester.view.resetPhysicalSize());
      await tester.pumpWidget(
        buildTestWidget(
          calendarState: EventCalendarState(
            selectedDate: DateTime(2026, 2, 20),
            selectedDayEvents: [createEvent(id: 1, symbol: '2330')],
          ),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      final list = tester.widget<ListView>(find.byType(ListView).last);
      final padding = list.padding?.resolve(TextDirection.ltr);
      expect(
        padding?.bottom ?? 0,
        greaterThanOrEqualTo(80),
        reason: '清單底部需留 FAB 迴避空間',
      );
    });

    testWidgets('wide right pane keeps structure when upcoming empty '
        '(hint + show-all action)', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(
        buildTestWidget(calendarState: EventCalendarState()),
      );
      await tester.pump(const Duration(seconds: 1));

      // 空清單不得讓右欄整片虛空：保留標題＋空狀態說明＋切全市場捷徑
      expect(find.text('calendar.upcomingTitle'), findsOneWidget);
      expect(find.text('calendar.noUpcomingWatchlistEvents'), findsOneWidget);
      final showAll = find.text('calendar.showAllEvents');
      expect(showAll, findsOneWidget);

      await tester.tap(showAll);
      await tester.pump();
      expect(
        lastFakeNotifier!.filters,
        contains(CalendarFilter.all),
        reason: '捷徑應切換篩選為全部',
      );
    });

    testWidgets('narrow cramped height: empty day state must not overflow', (
      tester,
    ) async {
      // 邏輯 560x625：上方（未來14天卡＋月曆＋chips）吃掉大半高度後，
      // Expanded 剩 ~80dp，空狀態 icon48+文字 需可縮放不得溢位
      tester.view.physicalSize = const Size(1680, 1875);
      addTearDown(() => tester.view.resetPhysicalSize());
      // 釘死 6 列月份(2026-08:週六起頭+31 天)——月曆列數 4~6 隨當月
      // 而變,不釘月份此測試只在 6 列月份翻紅(2026-08-01 跨月實發,
      // rowHeight 固定 52 時多一列剛好溢位 6px)。
      await tester.pumpWidget(
        buildTestWidget(
          focusedDay: DateTime(2026, 8, 20),
          calendarState: EventCalendarState(
            selectedDate: DateTime(2026, 8, 20),
            upcomingEvents: [createEvent(id: 9, symbol: '2330')],
          ),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      expect(tester.takeException(), isNull, reason: '不得 RenderFlex 溢位');
      expect(find.byIcon(Icons.event_busy), findsOneWidget);
    });

    testWidgets('narrow cramped height + 錯誤 banner:仍不得溢位(2026-08-01 複審)', (
      tester,
    ) async {
      // 錯誤 banner(MaterialBanner ≥52dp)是條件式節點,原本不在窄佈局
      // 動態 rowHeight 的固定高度預算內——「有舊資料+重整失敗+矮視窗+
      // 6 列月份」同時成立時,banner 高度直接吃掉 Expanded 預留、重現
      // 這批修復要解決的同型溢位。既有兩個測試各只蓋一半:cramped 測試
      // 無 error、error 測試用寬視窗。
      tester.view.physicalSize = const Size(1680, 1875);
      addTearDown(() => tester.view.resetPhysicalSize());
      await tester.pumpWidget(
        buildTestWidget(
          focusedDay: DateTime(2026, 8, 20), // 6 列月份
          calendarState: EventCalendarState(
            selectedDate: DateTime(2026, 8, 20),
            error: 'sync failed',
            events: {
              DateTime(2026, 8, 5): [
                createEvent(
                  id: 8,
                  symbol: '2330',
                  eventDate: DateTime(2026, 8, 5),
                ),
              ],
            },
            upcomingEvents: [createEvent(id: 9, symbol: '2330')],
          ),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      expect(tester.takeException(), isNull, reason: '不得 RenderFlex 溢位');
    });

    testWidgets('narrow chips row keeps FAB clearance at scroll end', (
      tester,
    ) async {
      // 短視窗下 FAB 會壓住 chips 列最後一顆（自訂備忘）；窄版需
      // 尾距讓它能捲出 FAB，寬版（chips 在左欄）不需要
      tester.view.physicalSize = const Size(1680, 2400); // 邏輯 560 → 單欄
      addTearDown(() => tester.view.resetPhysicalSize());
      await tester.pumpWidget(buildTestWidget());
      await tester.pump(const Duration(seconds: 1));

      final scroll = tester.widget<SingleChildScrollView>(
        find
            .ancestor(
              of: find.byType(FilterChip).first,
              matching: find.byType(SingleChildScrollView),
            )
            .first,
      );
      final padding = scroll.padding?.resolve(TextDirection.ltr);
      expect(
        padding?.right ?? 0,
        greaterThanOrEqualTo(88),
        reason: '窄版 chips 列尾端需留 FAB 迴避空間',
      );
    });

    testWidgets('shows error state', (tester) async {
      widenViewport(tester);
      await tester.pumpWidget(
        buildTestWidget(calendarState: EventCalendarState(error: 'DB error')),
      );
      await tester.pump(const Duration(seconds: 1));

      // Error should be displayed
      expect(find.byType(EventCalendarScreen), findsOneWidget);
    });
  });

  // ====================================================================
  // 跳月殘響 race 第三入口(2026-08-01 複審)
  //
  // _jumpToToday/_pickMonth 都設 _pendingFocusTarget 濾掉翻頁動畫的
  // 延遲殘響,但「未來14天」卡片點擊(同樣程式化改 _focusedDay、同樣
  // 觸發套件內部翻頁動畫)漏設——殘響會把剛設好的目標月踩回動畫中途
  // 的舊月(59-60 行註解描述、已在另兩入口修過的同一個 race)。
  // 測試直接呼叫 TableCalendar.onPageChanged 模擬殘響,免依賴動畫時序。
  // ====================================================================
  group('未來14天卡片跳月 race', () {
    testWidgets('🚨 點跨月卡片後,殘響 onPageChanged 不得踩回舊月', (tester) async {
      tester.view.physicalSize = const Size(1680, 2400); // 單欄
      addTearDown(() => tester.view.resetPhysicalSize());
      await tester.pumpWidget(
        buildTestWidget(
          focusedDay: DateTime(2026, 8, 5),
          calendarState: EventCalendarState(
            upcomingEvents: [
              createEvent(
                id: 9,
                symbol: '2330',
                title: 'CrossMonth',
                eventDate: DateTime(2026, 9, 10),
              ),
            ],
          ),
        ),
      );
      await tester.pump(const Duration(seconds: 1));

      await tester.tap(find.text('CrossMonth'));
      await tester.pump();

      // 模擬前一個翻頁動畫的延遲殘響:帶著舊月抵達
      final cal = tester.widget<TableCalendar<StockEventEntry>>(
        find.byType(TableCalendar<StockEventEntry>),
      );
      cal.onPageChanged!(DateTime(2026, 8, 1));
      await tester.pump();

      final calAfter = tester.widget<TableCalendar<StockEventEntry>>(
        find.byType(TableCalendar<StockEventEntry>),
      );
      expect(calAfter.focusedDay.month, 9, reason: '殘響(8月)不得踩掉剛跳去的目標月(9月)');
    });
  });
}
