import 'package:daredevil/core/exceptions/app_exception.dart';
import 'package:daredevil/data/database/app_database.dart';
import 'package:daredevil/data/remote/tpex_client.dart';
import 'package:daredevil/data/remote/twse_client.dart';
import 'package:daredevil/domain/services/update/dividend_syncer.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';

class MockAppDatabase extends Mock implements AppDatabase {
  @override
  Future<T> transaction<T>(Future<T> Function() action, {bool? requireNew}) {
    return action();
  }
}

class MockTwseClient extends Mock implements TwseClient {}

class MockTpexClient extends Mock implements TpexClient {}

class _FakeStockEventCompanion extends Fake implements StockEventCompanion {}

StockMasterEntry _stock(String symbol, String market) => StockMasterEntry(
  symbol: symbol,
  name: symbol,
  market: market,
  industry: '測試',
  isActive: true,
  updatedAt: DateTime(2026, 7, 17),
);

void main() {
  setUpAll(() {
    registerFallbackValue(<StockEventCompanion>[]);
    registerFallbackValue(<String>[]);
    registerFallbackValue(_FakeStockEventCompanion());
  });

  late MockAppDatabase db;
  late MockTwseClient twse;
  late MockTpexClient tpex;
  late DividendSyncer syncer;

  setUp(() {
    db = MockAppDatabase();
    twse = MockTwseClient();
    tpex = MockTpexClient();
    syncer = DividendSyncer(database: db, twseClient: twse, tpexClient: tpex);

    // 上市 2330、上櫃 5483 皆為已知股票
    when(
      () => db.getAllActiveStocks(),
    ).thenAnswer((_) async => [_stock('2330', 'TWSE'), _stock('5483', 'TPEX')]);
    when(
      () => db.deleteAutoGeneratedEventsByTypes(any()),
    ).thenAnswer((_) async {});
    when(() => db.insertStockEvent(any())).thenAnswer((_) async => 1);
    when(() => db.insertStockEvents(any())).thenAnswer((_) async {});
  });

  group('DividendSyncer 股東會破壞性寫入守衛', () {
    test('TWSE 失敗、TPEX 成功時不得全市場刪除股東會事件（保留 TWSE 既有資料）', () async {
      // TWSE 已宣告股利（含股東會）取得失敗（一般例外 → 被 catch；限流與網路錯誤
      // 則會 rethrow）
      when(
        () => twse.getDeclaredDividends(),
      ).thenThrow(Exception('twse transient boom'));
      // TPEX 股東會成功回一筆（上櫃 5483）
      when(() => tpex.getShareholderMeetings()).thenAnswer(
        (_) async => [
          TpexShareholderMeeting(
            symbol: '5483',
            companyName: '中美晶',
            meetingType: '股東常會',
            meetingDate: DateTime(2026, 8, 20),
            hasBoardElection: false,
            hasEVoting: true,
          ),
        ],
      );

      final result = await syncer.syncShareholderMeetings();

      // 核心斷言：TWSE 這個股東會來源失敗 → 不可執行全市場無差別刪除，
      // 否則會清掉 TWSE 上一輪正確寫入的上市公司股東會事件且無法補回。
      verifyNever(() => db.deleteAutoGeneratedEventsByTypes(any()));
      // 略過重建 → 不做任何部分插入
      verifyNever(() => db.insertStockEvents(any()));
      // 失敗有記錄
      expect(result.hasErrors, isTrue);
    });

    test('兩來源皆成功時仍照常重建股東會事件（既有行為保留）', () async {
      when(() => twse.getDeclaredDividends()).thenAnswer(
        (_) async => [
          TwseDeclaredDividend(
            symbol: '2330',
            companyName: '台積電',
            dividendYear: 2026,
            cashDividend: 4.0,
            stockDividend: 0.0,
            shareholderMeetingDate: DateTime(2026, 8, 15),
          ),
        ],
      );
      when(() => tpex.getShareholderMeetings()).thenAnswer(
        (_) async => [
          TpexShareholderMeeting(
            symbol: '5483',
            companyName: '中美晶',
            meetingType: '股東常會',
            meetingDate: DateTime(2026, 8, 20),
            hasBoardElection: false,
            hasEVoting: true,
          ),
        ],
      );

      final result = await syncer.syncShareholderMeetings();

      // 兩來源皆完整 → 全市場刪除 + 重建（各一筆：2330、5483）
      verify(
        () =>
            db.deleteAutoGeneratedEventsByTypes(const ['SHAREHOLDER_MEETING']),
      ).called(1);
      final batchArg =
          verify(() => db.insertStockEvents(captureAny())).captured.single
              as List<StockEventCompanion>;
      expect(batchArg, hasLength(2));
      expect(result.meetingEventsCreated, 2);
    });

    test('同 symbol 不同日期不得因去重 key 未補零互撞被丟(1/12 vs 11/2)', () async {
      // 2026-07-29 審查發現:key 用 '${year}${month}${day}' 無補零,
      // 2026-1-12 與 2026-11-2 都是 '2026112' → 後者被當重複靜默丟棄。
      // 常會+臨時會同 symbol 兩筆是真實情境。
      when(
        () => twse.getDeclaredDividends(),
      ).thenAnswer((_) async => <TwseDeclaredDividend>[]);
      when(() => tpex.getShareholderMeetings()).thenAnswer(
        (_) async => [
          TpexShareholderMeeting(
            symbol: '5483',
            companyName: '中美晶',
            meetingType: '股東常會',
            meetingDate: DateTime(2026, 1, 12),
            hasBoardElection: false,
            hasEVoting: true,
          ),
          TpexShareholderMeeting(
            symbol: '5483',
            companyName: '中美晶',
            meetingType: '股東臨時會',
            meetingDate: DateTime(2026, 11, 2),
            hasBoardElection: true,
            hasEVoting: true,
          ),
        ],
      );

      final result = await syncer.syncShareholderMeetings();

      final batchArg =
          verify(() => db.insertStockEvents(captureAny())).captured.single
              as List<StockEventCompanion>;
      expect(batchArg, hasLength(2));
      expect(result.meetingEventsCreated, 2);
    });

    // 限流與網路錯誤往上拋（由 UpdateService 決定中止或續跑），而且拋出前
    // 不可動既有股東會事件
    for (final (kind, error) in const [
      ('限流', RateLimitException('429')),
      ('網路錯誤', NetworkException('timeout')),
    ]) {
      test('上市來源$kind：往上拋，不刪不寫股東會事件', () async {
        when(() => twse.getDeclaredDividends()).thenThrow(error);
        when(() => tpex.getShareholderMeetings()).thenAnswer((_) async => []);

        await expectLater(
          syncer.syncShareholderMeetings(),
          throwsA(same(error)),
        );
        verifyNever(() => db.deleteAutoGeneratedEventsByTypes(any()));
        verifyNever(() => db.insertStockEvents(any()));
      });

      test('上櫃股東會$kind：往上拋，不刪不寫股東會事件', () async {
        when(() => twse.getDeclaredDividends()).thenAnswer(
          (_) async => [
            TwseDeclaredDividend(
              symbol: '2330',
              companyName: '台積電',
              dividendYear: 2026,
              cashDividend: 4.0,
              stockDividend: 0.0,
              shareholderMeetingDate: DateTime(2026, 8, 15),
            ),
          ],
        );
        when(() => tpex.getShareholderMeetings()).thenThrow(error);

        await expectLater(
          syncer.syncShareholderMeetings(),
          throwsA(same(error)),
        );
        verifyNever(() => db.deleteAutoGeneratedEventsByTypes(any()));
        verifyNever(() => db.insertStockEvents(any()));
      });
    }

    test('上市：不在主檔的代號、沒有股東會日期的列都不寫事件', () async {
      when(() => twse.getDeclaredDividends()).thenAnswer(
        (_) async => [
          TwseDeclaredDividend(
            symbol: '2330',
            companyName: '台積電',
            dividendYear: 2026,
            cashDividend: 4.0,
            stockDividend: 0.0,
            shareholderMeetingDate: DateTime(2026, 8, 15),
          ),
          TwseDeclaredDividend(
            symbol: '9999',
            companyName: '不在主檔',
            dividendYear: 2026,
            cashDividend: 1.0,
            stockDividend: 0.0,
            shareholderMeetingDate: DateTime(2026, 8, 16),
          ),
          // 在主檔、但這筆沒有股東會日期
          const TwseDeclaredDividend(
            symbol: '5483',
            companyName: '中美晶',
            dividendYear: 2026,
            cashDividend: 1.0,
            stockDividend: 0.0,
          ),
        ],
      );
      when(() => tpex.getShareholderMeetings()).thenAnswer((_) async => []);

      await syncer.syncShareholderMeetings();

      final batchArg =
          verify(() => db.insertStockEvents(captureAny())).captured.single
              as List<StockEventCompanion>;
      expect(batchArg.map((e) => e.symbol.value), ['2330']);
    });

    test('TPEX 股東會失敗、TWSE 成功時不得全市場刪除股東會事件', () async {
      when(() => twse.getDeclaredDividends()).thenAnswer(
        (_) async => [
          TwseDeclaredDividend(
            symbol: '2330',
            companyName: '台積電',
            dividendYear: 2026,
            cashDividend: 4.0,
            stockDividend: 0.0,
            shareholderMeetingDate: DateTime(2026, 8, 15),
          ),
        ],
      );
      when(
        () => tpex.getShareholderMeetings(),
      ).thenThrow(Exception('tpex transient boom'));

      final result = await syncer.syncShareholderMeetings();

      verifyNever(() => db.deleteAutoGeneratedEventsByTypes(any()));
      verifyNever(() => db.insertStockEvents(any()));
      expect(result.hasErrors, isTrue);
    });
  });
}
