import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';

import 'package:daredevil/core/exceptions/app_exception.dart';
import 'package:daredevil/data/database/app_database.dart';
import 'package:daredevil/data/repositories/event_repository.dart';
import 'package:daredevil/data/remote/tpex_client.dart';
import 'package:daredevil/data/remote/twse_client.dart';

class MockAppDatabase extends Mock implements AppDatabase {
  @override
  Future<T> transaction<T>(Future<T> Function() action, {bool? requireNew}) {
    return action();
  }
}

class MockTwseClient extends Mock implements TwseClient {}

class MockTpexClient extends Mock implements TpexClient {}

class FakeStockEventCompanion extends Fake implements StockEventCompanion {}

StockMasterEntry _stock(String symbol) => StockMasterEntry(
  symbol: symbol,
  name: '測試$symbol',
  market: 'TWSE',
  industry: '金融保險',
  isActive: true,
  updatedAt: DateTime(2026, 8, 1),
);

/// syncDividendEvents 換源重寫(2026-08-01):TWSE/TPEx 除權息預告表直建
/// 事件。驗收案例=2886 兆豐金 2026-08-13 除息 1.75(與其停券預告
/// 8/7-8/12 因果成對;原功能因 dividend_history 無日期而自上線空轉)。
void main() {
  setUpAll(() {
    registerFallbackValue(FakeStockEventCompanion());
    registerFallbackValue(<StockEventCompanion>[]);
  });

  late MockAppDatabase mockDb;
  late MockTwseClient mockTwse;
  late MockTpexClient mockTpex;
  late EventRepository repo;

  final mega2886 = ExRightPreannouncement(
    symbol: '2886',
    date: DateTime(2026, 8, 13),
    hasDividend: true,
    hasRights: false,
    cashDividend: 1.75,
  );

  setUp(() {
    mockDb = MockAppDatabase();
    mockTwse = MockTwseClient();
    mockTpex = MockTpexClient();
    repo = EventRepository(
      database: mockDb,
      twseClient: mockTwse,
      tpexClient: mockTpex,
    );
    when(
      () => mockDb.getAllActiveStocks(),
    ).thenAnswer((_) async => [_stock('2886'), _stock('3402')]);
    when(
      () => mockDb.deleteAutoGeneratedEventsByTypes(any()),
    ).thenAnswer((_) async {});
    when(() => mockDb.insertStockEvents(any())).thenAnswer((_) async {});
  });

  List<StockEventCompanion> captured() =>
      verify(() => mockDb.insertStockEvents(captureAny())).captured.single
          as List<StockEventCompanion>;

  test('🚨 2886 除息 8/13 建 EX_DIVIDEND 事件(帶現金股利描述)', () async {
    when(
      () => mockTwse.getExRightPreannouncements(),
    ).thenAnswer((_) async => [mega2886]);
    when(
      () => mockTpex.getExRightPreannouncements(),
    ).thenAnswer((_) async => const []);

    final result = await repo.syncDividendEvents();

    expect(result.exDividend, 1);
    expect(result.exRights, 0);
    verify(
      () => mockDb.deleteAutoGeneratedEventsByTypes(const [
        'EX_DIVIDEND',
        'EX_RIGHTS',
      ]),
    ).called(1);
    final c = captured().single;
    expect(c.eventType.value, 'EX_DIVIDEND');
    expect(c.eventDate.value, DateTime(2026, 8, 13));
    expect(c.title.value, '2886 除息');
    expect(c.description.value, contains('1.75'));
  });

  test('權息一列建兩事件;不在 stock_master 者(如 00400A)跳過防 FK 炸', () async {
    when(() => mockTwse.getExRightPreannouncements()).thenAnswer(
      (_) async => [
        ExRightPreannouncement(
          symbol: '3402',
          date: DateTime(2026, 8, 20),
          hasDividend: true,
          hasRights: true,
          cashDividend: 2.0,
          stockDividendRatio: 10.0,
        ),
        ExRightPreannouncement(
          symbol: '00400A',
          date: DateTime(2026, 8, 5),
          hasDividend: true,
          hasRights: false,
        ),
      ],
    );
    when(
      () => mockTpex.getExRightPreannouncements(),
    ).thenAnswer((_) async => const []);

    final result = await repo.syncDividendEvents();

    expect(result.total, 2, reason: '3402 權息=2 事件;00400A 不在主檔跳過');
    expect(result.exDividend, 1);
    expect(result.exRights, 1);
    final types = captured().map((c) => c.eventType.value).toSet();
    expect(types, {'EX_DIVIDEND', 'EX_RIGHTS'});
  });

  test('both-or-nothing:上櫃側失敗直接拋出,不得刪除既有事件', () async {
    when(
      () => mockTwse.getExRightPreannouncements(),
    ).thenAnswer((_) async => [mega2886]);
    when(
      () => mockTpex.getExRightPreannouncements(),
    ).thenThrow(const NetworkException('tpex down'));

    await expectLater(
      repo.syncDividendEvents(),
      throwsA(isA<NetworkException>()),
    );
    verifyNever(() => mockDb.deleteAutoGeneratedEventsByTypes(any()));
    verifyNever(() => mockDb.insertStockEvents(any()));
  });
}
