import 'package:daredevil/data/database/app_database.dart';
import 'package:daredevil/data/remote/twse_client.dart';
import 'package:daredevil/data/repositories/event_repository.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';

class MockAppDatabase extends Mock implements AppDatabase {
  @override
  Future<T> transaction<T>(Future<T> Function() action, {bool? requireNew}) {
    return action();
  }
}

class FakeStockEventCompanion extends Fake implements StockEventCompanion {}

class MockTwseClient extends Mock implements TwseClient {}

void main() {
  setUpAll(() {
    registerFallbackValue(FakeStockEventCompanion());
    registerFallbackValue(<StockEventCompanion>[]);
  });

  late MockAppDatabase mockDb;
  late EventRepository repository;

  setUp(() {
    mockDb = MockAppDatabase();
    repository = EventRepository(database: mockDb);
  });

  // ==========================================
  // 事件查詢
  // ==========================================
  group('getEventsInRange', () {
    test('delegates to database', () async {
      final start = DateTime(2025, 1, 1);
      final end = DateTime(2025, 1, 31);
      final events = [
        StockEventEntry(
          id: 1,
          symbol: '2330',
          eventType: 'EX_DIVIDEND',
          eventDate: DateTime(2025, 1, 15),
          title: '2330 除息',
          isAutoGenerated: true,
          createdAt: DateTime(2025, 1, 1),
        ),
      ];

      when(
        () =>
            mockDb.getEventsInRange(start, end, symbols: any(named: 'symbols')),
      ).thenAnswer((_) async => events);

      final result = await repository.getEventsInRange(start, end);

      expect(result, equals(events));
      verify(
        () =>
            mockDb.getEventsInRange(start, end, symbols: any(named: 'symbols')),
      ).called(1);
    });
  });

  // ==========================================
  // 事件操作
  // ==========================================
  group('addCustomEvent', () {
    test('inserts CUSTOM event with correct fields', () async {
      when(() => mockDb.insertStockEvent(any())).thenAnswer((_) async => 42);

      final eventDate = DateTime(2025, 3, 15);
      final result = await repository.addCustomEvent(
        symbol: '2330',
        eventDate: eventDate,
        title: '法說會',
        description: '第一季法說會',
      );

      expect(result, equals(42));

      final captured =
          verify(() => mockDb.insertStockEvent(captureAny())).captured.single
              as StockEventCompanion;
      expect(captured.eventType.value, equals('CUSTOM'));
      expect(captured.eventDate.value, equals(eventDate));
      expect(captured.title.value, equals('法說會'));
      expect(captured.description.value, equals('第一季法說會'));
      expect(captured.symbol.value, equals('2330'));
    });

    test('allows null symbol for personal memo events', () async {
      when(() => mockDb.insertStockEvent(any())).thenAnswer((_) async => 43);

      await repository.addCustomEvent(
        eventDate: DateTime(2025, 3, 15),
        title: '個人備忘',
      );

      final captured =
          verify(() => mockDb.insertStockEvent(captureAny())).captured.single
              as StockEventCompanion;
      // addCustomEvent passes Value(symbol) where symbol is null
      expect(captured.symbol.value, isNull);
    });
  });

  group('deleteEvent', () {
    test('delegates to database', () async {
      when(() => mockDb.deleteStockEvent(42)).thenAnswer((_) async {});

      await repository.deleteEvent(42);

      verify(() => mockDb.deleteStockEvent(42)).called(1);
    });
  });

  // ==========================================
  // 除權息日同步
  // ==========================================
  group('rocDateToDateTime', () {
    test('民國年字串轉西元 DateTime', () {
      expect(rocDateToDateTime('1150730'), DateTime(2026, 7, 30));
      expect(rocDateToDateTime('1150101'), DateTime(2026, 1, 1));
      expect(rocDateToDateTime('bad'), isNull);
      expect(rocDateToDateTime(''), isNull);
      // 2/30 這種不存在的日期不得溢位進位成 3/2
      expect(rocDateToDateTime('1150230'), isNull);
    });
  });

  group('syncInvestorConferenceEvents（讀已存公告，不重打 API）', () {
    setUp(() {
      // 不再依賴 client：改讀 DB 已存的重大訊息公告
      repository = EventRepository(database: mockDb);
      when(() => mockDb.getWatchlist()).thenAnswer(
        (_) async => [
          WatchlistEntry(symbol: '1537', createdAt: DateTime(2026, 1, 1)),
        ],
      );
      when(() => mockDb.getPortfolioPositions()).thenAnswer((_) async => []);
    });

    test('從已存公告文字抽法說會開會日→EARNINGS（API 為空也能建）', () async {
      when(() => mockDb.getMaterialAnnouncements()).thenAnswer(
        (_) async => [
          (
            symbol: '1537',
            text:
                '1537 廣隆｜受邀參加法人說明會\n'
                '1.召開法人說明會之日期：115/07/24\n2.時間：14時',
          ),
          (symbol: '9999', text: '9999 X｜受邀參加法人說明會\n召開法人說明會之日期：115/07/25'),
        ],
      );
      when(
        () => mockDb.getAutoGeneratedEventsByType('EARNINGS'),
      ).thenAnswer((_) async => []);
      when(() => mockDb.insertStockEvents(any())).thenAnswer((_) async {});

      final count = await repository.syncInvestorConferenceEvents();

      expect(count, 1, reason: '9999 非自選略過');
      final captured =
          (verify(() => mockDb.insertStockEvents(captureAny())).captured.single
                  as List<StockEventCompanion>)
              .toList();
      expect(captured.single.symbol.value, '1537');
      expect(captured.single.eventType.value, 'EARNINGS');
      expect(captured.single.eventDate.value, DateTime(2026, 7, 24));
      expect(captured.single.title.value, contains('法說會'));
    });

    test('非法說會公告不建事件', () async {
      when(
        () => mockDb.getMaterialAnnouncements(),
      ).thenAnswer((_) async => [(symbol: '1537', text: '1537 廣隆｜公告更名')]);
      when(
        () => mockDb.getAutoGeneratedEventsByType('EARNINGS'),
      ).thenAnswer((_) async => []);

      final count = await repository.syncInvestorConferenceEvents();
      expect(count, 0);
      verifyNever(() => mockDb.insertStockEvents(any()));
    });

    test('已存同（symbol,日）事件則跳過', () async {
      when(() => mockDb.getMaterialAnnouncements()).thenAnswer(
        (_) async => [
          (symbol: '1537', text: '1537 廣隆｜法人說明會\n召開法人說明會之日期：115/07/24'),
        ],
      );
      when(() => mockDb.getAutoGeneratedEventsByType('EARNINGS')).thenAnswer(
        (_) async => [
          StockEventEntry(
            id: 1,
            symbol: '1537',
            eventType: 'EARNINGS',
            eventDate: DateTime(2026, 7, 24),
            title: '1537 法說會',
            isAutoGenerated: true,
            createdAt: DateTime(2026, 7, 23),
          ),
        ],
      );

      final count = await repository.syncInvestorConferenceEvents();
      expect(count, 0);
      verifyNever(() => mockDb.insertStockEvents(any()));
    });
  });

  group('syncShortSuspensionEvents', () {
    late MockTwseClient mockClient;

    setUp(() {
      mockClient = MockTwseClient();
      repository = EventRepository(database: mockDb, twseClient: mockClient);
    });

    test('停券預告過濾到自選/持倉、寫入事件並回傳筆數', () async {
      when(() => mockDb.getWatchlist()).thenAnswer(
        (_) async => [
          WatchlistEntry(symbol: '3231', createdAt: DateTime(2026, 1, 1)),
        ],
      );
      when(() => mockDb.getPortfolioPositions()).thenAnswer((_) async => []);
      when(() => mockClient.getShortSellingSuspensions()).thenAnswer(
        (_) async => [
          const TwseShortSuspension(
            code: '3231',
            name: '緯創',
            startDate: '1150730',
            endDate: '1150804',
            reason: '股東會',
          ),
          const TwseShortSuspension(
            code: '9999',
            name: '非自選',
            startDate: '1150730',
            endDate: '1150804',
            reason: '除息',
          ),
        ],
      );
      when(
        () => mockDb.deleteAutoGeneratedEventsByTypes(any()),
      ).thenAnswer((_) async {});
      when(() => mockDb.insertStockEvents(any())).thenAnswer((_) async {});

      final count = await repository.syncShortSuspensionEvents();

      expect(count, 1);
      verify(
        () => mockDb.deleteAutoGeneratedEventsByTypes(['SHORT_SUSPENSION']),
      ).called(1);
      final captured =
          (verify(() => mockDb.insertStockEvents(captureAny())).captured.single
                  as List<StockEventCompanion>)
              .toList();
      expect(captured, hasLength(1));
      expect(captured.first.symbol.value, '3231');
      expect(captured.first.eventType.value, 'SHORT_SUSPENSION');
      expect(captured.first.eventDate.value, DateTime(2026, 7, 30));
      expect(captured.first.title.value, contains('停券'));
      expect(captured.first.description.value, contains('股東會'));
      expect(captured.first.isAutoGenerated.value, isTrue);
    });

    test('未注入 client 時回 0 不打 API', () async {
      repository = EventRepository(database: mockDb);
      final count = await repository.syncShortSuspensionEvents();
      expect(count, 0);
    });
  });

  group('syncDisposalEndEvents', () {
    TradingWarningEntry warning({
      required String symbol,
      DateTime? endDate,
      bool isActive = true,
    }) {
      return TradingWarningEntry(
        symbol: symbol,
        date: DateTime(2026, 7, 1),
        warningType: 'DISPOSAL',
        isActive: isActive,
        disposalEndDate: endDate,
      );
    }

    test('從 active DISPOSAL 產生出關事件（先刪舊、再插入、回傳筆數）', () async {
      when(() => mockDb.getActiveWarningsByType('DISPOSAL')).thenAnswer(
        (_) async => [
          warning(symbol: '3260', endDate: DateTime(2026, 8, 5)),
          warning(symbol: '4939', endDate: DateTime(2026, 8, 12)),
        ],
      );
      when(
        () => mockDb.deleteAutoGeneratedEventsByTypes(any()),
      ).thenAnswer((_) async {});
      when(() => mockDb.insertStockEvents(any())).thenAnswer((_) async {});

      final count = await repository.syncDisposalEndEvents();

      expect(count, 2);
      verify(
        () => mockDb.deleteAutoGeneratedEventsByTypes(['DISPOSAL_END']),
      ).called(1);
      final captured =
          (verify(() => mockDb.insertStockEvents(captureAny())).captured.single
                  as List<StockEventCompanion>)
              .toList();
      expect(captured, hasLength(2));
      expect(captured.first.eventType.value, 'DISPOSAL_END');
      expect(captured.first.symbol.value, '3260');
      expect(captured.first.eventDate.value, DateTime(2026, 8, 5));
      expect(captured.first.isAutoGenerated.value, isTrue);
      expect(captured.first.title.value, contains('處置結束'));
    });

    test('無 disposal_end_date 的處置股跳過', () async {
      when(
        () => mockDb.getActiveWarningsByType('DISPOSAL'),
      ).thenAnswer((_) async => [warning(symbol: '3260', endDate: null)]);
      when(
        () => mockDb.deleteAutoGeneratedEventsByTypes(any()),
      ).thenAnswer((_) async {});
      when(() => mockDb.insertStockEvents(any())).thenAnswer((_) async {});

      final count = await repository.syncDisposalEndEvents();

      expect(count, 0);
      final batchArg =
          verify(() => mockDb.insertStockEvents(captureAny())).captured.single
              as List<StockEventCompanion>;
      expect(batchArg, isEmpty, reason: '缺 end date 者不得混入批次');
    });
  });

  // syncDividendEvents 的行為測試已隨 2026-08-01 換源重寫搬遷至
  // event_repository_exright_test.dart(資料源由舊股利表改為
  // TWSE/TPEx 除權息預告表,舊測試斷言的是已移除的 watchlist-scoped
  // 舊股利表讀取行為)。
  group('syncDividendEvents(換源後)', () {
    test('client 未注入回零、不動既有事件', () async {
      final result = await repository.syncDividendEvents();

      expect(result.total, 0);
      verifyNever(() => mockDb.deleteAutoGeneratedEventsByTypes(any()));
      verifyNever(() => mockDb.insertStockEvents(any()));
    });
  });
}
