import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';

import 'package:daredevil/core/theme/app_theme.dart';
import 'package:daredevil/data/database/app_database.dart';
import 'package:daredevil/presentation/providers/event_calendar_provider.dart';
import 'package:daredevil/core/theme/design_tokens.dart';

/// 事件列表項
class EventListTile extends StatelessWidget {
  const EventListTile({
    super.key,
    required this.event,
    this.onTap,
    this.onDelete,
  });

  final StockEventEntry event;
  final VoidCallback? onTap;
  final VoidCallback? onDelete;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final type = EventType.fromValue(event.eventType);
    // 左框（solid）走主題調和色；icon 底 tint 維持 .color@0.15（守門組合）
    final color = type.colorFor(theme.brightness);

    return Dismissible(
      key: ValueKey(event.id),
      direction: event.isAutoGenerated
          ? DismissDirection.none
          : DismissDirection.endToStart,
      confirmDismiss: (_) async {
        onDelete?.call();
        return false;
      },
      background: Container(
        alignment: Alignment.centerRight,
        padding: const EdgeInsets.only(right: 16),
        color: AppTheme.errorColor,
        child: const Icon(Icons.delete, color: Colors.white),
      ),
      child: Semantics(
        button: true,
        label: event.title,
        onTap: onTap,
        child: GestureDetector(
          onTap: onTap,
          child: Container(
            margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: theme.colorScheme.surfaceContainerLow,
              borderRadius: BorderRadius.circular(DesignTokens.radiusLg),
              border: Border(left: BorderSide(color: color, width: 4)),
            ),
            child: Row(
              children: [
                // 事件類型圖示
                Container(
                  width: 36,
                  height: 36,
                  decoration: BoxDecoration(
                    color: type.color.withValues(alpha: 0.15),
                    borderRadius: BorderRadius.circular(DesignTokens.radiusMd),
                  ),
                  child: Icon(
                    type.icon,
                    size: 20,
                    color: type.onTintFor(theme.brightness),
                  ),
                ),
                const SizedBox(width: 12),
                // 內容
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          Container(
                            padding: const EdgeInsets.symmetric(
                              horizontal: 6,
                              vertical: 2,
                            ),
                            decoration: BoxDecoration(
                              // tint 底維持 .color（守門組合），同上方 icon 底
                              color: type.color.withValues(alpha: 0.15),
                              borderRadius: BorderRadius.circular(
                                DesignTokens.radiusXs,
                              ),
                            ),
                            child: Text(
                              type.i18nKey.tr(),
                              style: theme.textTheme.labelSmall?.copyWith(
                                color: type.onTintFor(theme.brightness),
                                fontWeight: FontWeight.w600,
                              ),
                            ),
                          ),
                          if (event.isAutoGenerated) ...[
                            const SizedBox(width: 6),
                            Icon(
                              Icons.auto_awesome,
                              size: 14,
                              color: theme.colorScheme.outline,
                            ),
                          ],
                        ],
                      ),
                      const SizedBox(height: 4),
                      Text(
                        event.title,
                        style: theme.textTheme.bodyMedium?.copyWith(
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      if (event.description != null &&
                          event.description!.isNotEmpty) ...[
                        const SizedBox(height: 2),
                        Text(
                          event.description!,
                          style: theme.textTheme.bodySmall?.copyWith(
                            color: theme.colorScheme.outline,
                          ),
                          maxLines: 2,
                          overflow: TextOverflow.ellipsis,
                        ),
                      ],
                    ],
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
