import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import 'package:daredevil/core/constants/app_routes.dart';
import 'package:daredevil/core/theme/app_theme.dart';
import 'package:daredevil/core/utils/number_formatter.dart';
import 'package:daredevil/core/utils/logger.dart';
import 'package:daredevil/core/theme/design_tokens.dart';
import 'package:daredevil/data/database/app_database.dart';
import 'package:daredevil/presentation/providers/event_calendar_provider.dart';
import 'package:daredevil/presentation/providers/providers.dart';
import 'package:daredevil/presentation/screens/calendar/widgets/add_event_sheet.dart';
import 'package:daredevil/presentation/widgets/common/drag_handle.dart';
import 'package:daredevil/presentation/widgets/app_bottom_sheet.dart';

/// 顯示事件詳情 Bottom Sheet
void showEventDetailSheet(
  BuildContext context,
  StockEventEntry event, {
  VoidCallback? onDelete,
}) {
  showAppBottomSheet(
    context: context,
    isScrollControlled: true,
    useSafeArea: true,
    builder: (context) => EventDetailSheet(event: event, onDelete: onDelete),
  );
}

/// 事件詳情
class EventDetailSheet extends ConsumerStatefulWidget {
  const EventDetailSheet({super.key, required this.event, this.onDelete});

  final StockEventEntry event;
  final VoidCallback? onDelete;

  @override
  ConsumerState<EventDetailSheet> createState() => _EventDetailSheetState();
}

class _EventDetailSheetState extends ConsumerState<EventDetailSheet> {
  DailyPriceEntry? _priceData;
  bool _priceLoaded = false;

  @override
  void initState() {
    super.initState();
    _loadPriceData();
  }

  Future<void> _loadPriceData() async {
    if (widget.event.symbol == null) return;
    try {
      final priceRepo = ref.read(priceRepositoryProvider);
      final price = await priceRepo.getPriceOnDate(
        widget.event.symbol!,
        widget.event.eventDate,
      );
      if (mounted) {
        setState(() {
          _priceData = price;
          _priceLoaded = true;
        });
      }
    } catch (e) {
      AppLogger.debug('EventDetailSheet', '載入價格失敗: $e');
      if (mounted) setState(() => _priceLoaded = true);
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final event = widget.event;
    final type = EventType.fromValue(event.eventType);
    // badge tint 維持 .color@0.15＋onTintFor 前景（守門測試組合）；
    // 本 sheet 無 solid 識別色裝飾，不需 colorFor

    return Padding(
      padding: EdgeInsets.only(
        left: DesignTokens.spacing20,
        right: DesignTokens.spacing20,
        bottom: MediaQuery.of(context).padding.bottom + DesignTokens.spacing16,
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const DragHandle(),
          const SizedBox(height: DesignTokens.spacing16),

          // 事件類型 badge
          Row(
            children: [
              Container(
                padding: const EdgeInsets.symmetric(
                  horizontal: DesignTokens.spacing10,
                  vertical: DesignTokens.spacing4,
                ),
                decoration: BoxDecoration(
                  color: type.color.withValues(alpha: 0.15),
                  borderRadius: BorderRadius.circular(DesignTokens.radiusSm),
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Icon(
                      type.icon,
                      size: 16,
                      color: type.onTintFor(theme.brightness),
                    ),
                    const SizedBox(width: DesignTokens.spacing4),
                    Text(
                      type.i18nKey.tr(),
                      style: theme.textTheme.labelMedium?.copyWith(
                        color: type.onTintFor(theme.brightness),
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ],
                ),
              ),
              if (event.isAutoGenerated) ...[
                const SizedBox(width: DesignTokens.spacing8),
                Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: DesignTokens.spacing8,
                    vertical: DesignTokens.spacing4,
                  ),
                  decoration: BoxDecoration(
                    color: theme.colorScheme.surfaceContainerHigh,
                    borderRadius: BorderRadius.circular(DesignTokens.radiusSm),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Icon(
                        Icons.auto_awesome,
                        size: 14,
                        color: theme.colorScheme.outline,
                      ),
                      const SizedBox(width: DesignTokens.spacing4),
                      Text(
                        'calendar.autoGenerated'.tr(),
                        style: theme.textTheme.labelSmall?.copyWith(
                          color: theme.colorScheme.outline,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ],
          ),
          const SizedBox(height: DesignTokens.spacing16),

          // 標題
          Text(
            event.title,
            style: theme.textTheme.titleMedium?.copyWith(
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: DesignTokens.spacing8),

          // 日期
          Row(
            children: [
              Icon(
                Icons.calendar_today,
                size: 16,
                color: theme.colorScheme.outline,
              ),
              const SizedBox(width: DesignTokens.spacing6),
              Text(
                DateFormat(
                  'yyyy-MM-dd (E)',
                  context.locale.toString(),
                ).format(event.eventDate),
                style: theme.textTheme.bodyMedium?.copyWith(
                  color: theme.colorScheme.onSurfaceVariant,
                ),
              ),
            ],
          ),

          // Description（完整顯示）
          if (event.description != null && event.description!.isNotEmpty) ...[
            const SizedBox(height: DesignTokens.spacing12),
            ..._buildDescription(event.description!),
          ],

          // 股價資訊
          if (event.symbol != null && _priceLoaded && _priceData != null) ...[
            const SizedBox(height: DesignTokens.spacing12),
            _buildPriceInfo(theme),
          ],

          // Symbol chip + 查看個股按鈕
          if (event.symbol != null) ...[
            const SizedBox(height: DesignTokens.spacing16),
            const Divider(),
            const SizedBox(height: DesignTokens.spacing12),
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: DesignTokens.spacing10,
                    vertical: DesignTokens.spacing6,
                  ),
                  decoration: BoxDecoration(
                    color: theme.colorScheme.primaryContainer,
                    borderRadius: BorderRadius.circular(DesignTokens.radiusSm),
                  ),
                  child: Text(
                    event.symbol!,
                    style: theme.textTheme.labelLarge?.copyWith(
                      color: theme.colorScheme.onPrimaryContainer,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
                const Spacer(),
                FilledButton.icon(
                  onPressed: () {
                    final router = GoRouter.of(context);
                    Navigator.pop(context);
                    router.push(AppRoutes.stockDetail(event.symbol!));
                  },
                  icon: const Icon(Icons.trending_up, size: 18),
                  label: Text('calendar.viewStock'.tr()),
                ),
              ],
            ),
          ],

          // 編輯 / 刪除按鈕（僅限手動事件）
          if (!event.isAutoGenerated && widget.onDelete != null) ...[
            const SizedBox(height: DesignTokens.spacing16),
            const Divider(),
            const SizedBox(height: DesignTokens.spacing12),
            Row(
              children: [
                Expanded(
                  child: OutlinedButton.icon(
                    onPressed: () {
                      final nav = Navigator.of(context);
                      nav.pop();
                      // 使用 navigator 的 overlay context 避免 deactivated context
                      final parentContext = nav.context;
                      showAppBottomSheet(
                        context: parentContext,
                        isScrollControlled: true,
                        useSafeArea: true,
                        builder: (_) => AddEventSheet(existingEvent: event),
                      );
                    },
                    icon: const Icon(Icons.edit_outlined, size: 18),
                    label: Text('calendar.editEvent'.tr()),
                  ),
                ),
                const SizedBox(width: DesignTokens.spacing12),
                Expanded(
                  child: OutlinedButton.icon(
                    onPressed: () {
                      Navigator.pop(context);
                      widget.onDelete!();
                    },
                    icon: const Icon(Icons.delete_outline, size: 18),
                    label: Text('calendar.deleteEvent'.tr()),
                    style: OutlinedButton.styleFrom(
                      foregroundColor: theme.colorScheme.error,
                      side: BorderSide(color: theme.colorScheme.error),
                    ),
                  ),
                ),
              ],
            ),
          ],
        ],
      ),
    );
  }

  Widget _buildPriceInfo(ThemeData theme) {
    final price = _priceData!;
    final change = price.priceChange;
    final close = price.close;
    final prevClose = (close != null && change != null) ? close - change : null;
    final changePercent = (prevClose != null && prevClose > 0)
        ? (change! / prevClose * 100)
        : null;
    final priceColor = context.priceColor(change);

    return Container(
      padding: const EdgeInsets.all(DesignTokens.spacing12),
      decoration: BoxDecoration(
        color: theme.colorScheme.surfaceContainerLow,
        borderRadius: BorderRadius.circular(DesignTokens.radiusMd),
      ),
      child: Row(
        children: [
          Icon(Icons.show_chart, size: 18, color: theme.colorScheme.outline),
          const SizedBox(width: DesignTokens.spacing8),
          Text(
            close?.toStringAsFixed(2) ?? '—',
            style: theme.textTheme.titleSmall?.copyWith(
              fontWeight: FontWeight.bold,
              color: priceColor,
            ),
          ),
          if (change != null) ...[
            const SizedBox(width: DesignTokens.spacing8),
            Text(
              AppNumberFormat.signedFixed(change, decimals: 2),
              style: theme.textTheme.bodySmall?.copyWith(color: priceColor),
            ),
          ],
          if (changePercent != null) ...[
            const SizedBox(width: DesignTokens.spacing4),
            Text(
              '(${AppNumberFormat.signedPercent(changePercent, decimals: 2)})',
              style: theme.textTheme.bodySmall?.copyWith(color: priceColor),
            ),
          ],
        ],
      ),
    );
  }

  /// 建構 description 區塊
  List<Widget> _buildDescription(String description) {
    final theme = Theme.of(context);
    final type = EventType.fromValue(widget.event.eventType);

    // 股東會事件：解析 '|' 分隔的結構化描述
    if (type == EventType.shareholderMeeting && description.contains('|')) {
      final parts = description
          .split('|')
          .map((s) => s.trim())
          .where((s) => s.isNotEmpty);
      return [
        Wrap(
          spacing: DesignTokens.spacing8,
          runSpacing: DesignTokens.spacing6,
          children: parts.map((part) {
            final icon = _meetingBadgeIcon(part);
            return Chip(
              avatar: icon != null ? Icon(icon, size: 16) : null,
              label: Text(part),
              visualDensity: VisualDensity.compact,
              materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
            );
          }).toList(),
        ),
      ];
    }

    // 一般事件：純文字顯示
    return [
      Text(
        description,
        style: theme.textTheme.bodyMedium?.copyWith(
          color: theme.colorScheme.onSurfaceVariant,
        ),
      ),
    ];
  }

  IconData? _meetingBadgeIcon(String text) {
    if (text.contains('改選') || text.contains('Election')) {
      return Icons.how_to_vote_outlined;
    }
    if (text.contains('電子投票') || text.contains('E-Voting')) {
      return Icons.smartphone_outlined;
    }
    return Icons.location_on_outlined;
  }
}
