import 'dart:async';

import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:mocktail/mocktail.dart';

import 'package:daredevil/core/utils/clock.dart';
import 'package:daredevil/data/database/app_database.dart';
import 'package:daredevil/data/repositories/event_repository.dart';
import 'package:daredevil/presentation/providers/providers.dart';
import 'package:daredevil/presentation/providers/event_calendar_provider.dart';

// ==========================================
// Mocks
// ==========================================

class MockAppDatabase extends Mock implements AppDatabase {}

class MockEventRepository extends Mock implements EventRepository {}

class _FakeClock implements AppClock {
  _FakeClock(this._now);
  final DateTime _now;

  @override
  DateTime now() => _now;
}

// ==========================================
// Test Helpers
// ==========================================

StockEventEntry createEvent({
  int id = 1,
  String? symbol,
  String eventType = 'EX_DIVIDEND',
  DateTime? eventDate,
  String title = 'Test Event',
  String? description,
  bool isAutoGenerated = false,
  DateTime? createdAt,
}) {
  return StockEventEntry(
    id: id,
    symbol: symbol,
    eventType: eventType,
    eventDate: eventDate ?? DateTime(2026, 2, 15),
    title: title,
    description: description,
    isAutoGenerated: isAutoGenerated,
    createdAt: createdAt ?? DateTime(2026, 2, 1),
  );
}

// ==========================================
// Tests
// ==========================================

void main() {
  late MockAppDatabase mockDb;
  late MockEventRepository mockEventRepo;
  late _FakeClock fakeClock;
  late ProviderContainer container;

  setUpAll(() {
    registerFallbackValue(DateTime(2026));
  });

  setUp(() {
    mockDb = MockAppDatabase();
    mockEventRepo = MockEventRepository();
    fakeClock = _FakeClock(DateTime(2026, 2, 15, 10, 30));

    // 預設 filter 已改 watchlistOnly：loadMonthEvents 一律會先讀
    // watchlist 解析 filterSymbols；同步流程也會重建處置出關事件。
    when(() => mockDb.getWatchlist()).thenAnswer((_) async => []);
    when(
      () => mockEventRepo.syncDisposalEndEvents(),
    ).thenAnswer((_) async => 0);
    when(
      () => mockEventRepo.syncShortSuspensionEvents(),
    ).thenAnswer((_) async => 0);
    when(
      () => mockEventRepo.syncInvestorConferenceEvents(),
    ).thenAnswer((_) async => 0);

    container = ProviderContainer(
      overrides: [
        databaseProvider.overrideWithValue(mockDb),
        eventRepositoryProvider.overrideWithValue(mockEventRepo),
        appClockProvider.overrideWithValue(fakeClock),
      ],
    );
  });

  tearDown(() {
    container.dispose();
  });

  // ==========================================
  // EventType
  // ==========================================

  group('EventType', () {
    test('fromValue parses known types', () {
      expect(EventType.fromValue('EX_DIVIDEND'), EventType.exDividend);
      expect(EventType.fromValue('EX_RIGHTS'), EventType.exRights);
      expect(EventType.fromValue('EARNINGS'), EventType.earnings);
      expect(EventType.fromValue('CUSTOM'), EventType.custom);
    });

    test('fromValue defaults to custom for unknown', () {
      expect(EventType.fromValue('UNKNOWN'), EventType.custom);
    });

    test('i18nKey returns correct keys', () {
      expect(EventType.exDividend.i18nKey, 'calendar.typeExDividend');
      expect(EventType.exRights.i18nKey, 'calendar.typeExRights');
      expect(EventType.earnings.i18nKey, 'calendar.typeEarnings');
      expect(EventType.custom.i18nKey, 'calendar.typeCustom');
    });

    test('value property contains expected strings', () {
      expect(EventType.exDividend.value, 'EX_DIVIDEND');
      expect(EventType.exRights.value, 'EX_RIGHTS');
      expect(EventType.earnings.value, 'EARNINGS');
      expect(EventType.custom.value, 'CUSTOM');
    });
  });

  // ==========================================
  // EventCalendarState
  // ==========================================

  group('EventType.disposalEnd', () {
    test('fromValue 對應 DISPOSAL_END', () {
      expect(EventType.fromValue('DISPOSAL_END'), EventType.disposalEnd);
      expect(EventType.disposalEnd.value, 'DISPOSAL_END');
      expect(
        EventType.fromValue('SHORT_SUSPENSION'),
        EventType.shortSuspension,
      );
    });
  });

  group('upcoming 事件與篩選一致', () {
    test('watchlistOnly 預設下 upcoming 也以自選 symbols 過濾', () async {
      when(() => mockDb.getWatchlist()).thenAnswer(
        (_) async => [
          WatchlistEntry(symbol: '2330', createdAt: DateTime(2026, 1, 1)),
        ],
      );
      when(
        () => mockEventRepo.getEventsInRange(
          any(),
          any(),
          symbols: any(named: 'symbols'),
        ),
      ).thenAnswer((_) async => []);

      final notifier = container.read(eventCalendarProvider.notifier);
      await notifier.init();

      // upcoming 視窗＝fakeClock 今天（2026-02-15）起算
      final captured = verify(
        () => mockEventRepo.getEventsInRange(
          captureAny(),
          any(),
          symbols: captureAny(named: 'symbols'),
        ),
      ).captured;
      var found = false;
      for (var i = 0; i < captured.length; i += 2) {
        final start = captured[i] as DateTime;
        if (start == DateTime(2026, 2, 15)) {
          expect(captured[i + 1], [
            '2330',
          ], reason: '未來14天清單必須套用相同的自選過濾（畫面一致性）');
          found = true;
        }
      }
      expect(found, isTrue, reason: '應有 upcoming 範圍查詢');
    });

    test('setFilter 也刷新 upcoming（切回全部後 upcoming 不再過濾）', () async {
      when(
        () => mockEventRepo.getEventsInRange(
          any(),
          any(),
          symbols: any(named: 'symbols'),
        ),
      ).thenAnswer((_) async => []);

      final notifier = container.read(eventCalendarProvider.notifier);
      await notifier.init();
      await notifier.setFilter(CalendarFilter.all);

      final captured = verify(
        () => mockEventRepo.getEventsInRange(
          captureAny(),
          any(),
          symbols: captureAny(named: 'symbols'),
        ),
      ).captured;
      var upcomingCalls = 0;
      Object? lastSymbols = 'sentinel';
      for (var i = 0; i < captured.length; i += 2) {
        if (captured[i] == DateTime(2026, 2, 15)) {
          upcomingCalls++;
          lastSymbols = captured[i + 1];
        }
      }
      expect(upcomingCalls, 2, reason: 'init＋setFilter 各刷新一次 upcoming');
      expect(lastSymbols, isNull, reason: '切回全部後 upcoming 不過濾');
    });

    test('visibleUpcomingEvents 套用類型篩選', () {
      final state = EventCalendarState(
        upcomingEvents: [
          StockEventEntry(
            id: 1,
            symbol: '2330',
            eventType: 'EX_DIVIDEND',
            eventDate: DateTime(2026, 2, 20),
            title: '除息',
            isAutoGenerated: true,
            createdAt: DateTime(2026, 2, 1),
          ),
          StockEventEntry(
            id: 2,
            symbol: '2317',
            eventType: 'SHAREHOLDER_MEETING',
            eventDate: DateTime(2026, 2, 21),
            title: '股東會',
            isAutoGenerated: true,
            createdAt: DateTime(2026, 2, 1),
          ),
        ],
        selectedEventTypes: EventType.values.toSet()
          ..remove(EventType.shareholderMeeting),
      );

      expect(state.visibleUpcomingEvents.map((e) => e.title), ['除息']);
    });
  });

  group('EventCalendarState', () {
    test('has correct default values', () {
      final state = EventCalendarState();

      expect(state.focusedMonth, isNull);
      expect(state.selectedDate, isNull);
      expect(state.events, isEmpty);
      expect(state.selectedDayEvents, isEmpty);
      expect(state.filter, CalendarFilter.watchlistOnly);
      expect(state.isLoading, isFalse);
      expect(state.error, isNull);
    });

    test('copyWith preserves unset values', () {
      final state = EventCalendarState(
        focusedMonth: DateTime(2026, 2),
        filter: CalendarFilter.watchlistOnly,
        isLoading: true,
      );

      final copied = state.copyWith();
      expect(copied.focusedMonth, DateTime(2026, 2));
      expect(copied.filter, CalendarFilter.watchlistOnly);
      expect(copied.isLoading, isTrue);
    });

    test('copyWith with sentinel handles error correctly', () {
      final state = EventCalendarState(error: 'old error');

      final preserved = state.copyWith();
      expect(preserved.error, 'old error');

      final cleared = state.copyWith(error: null);
      expect(cleared.error, isNull);

      final updated = state.copyWith(error: 'new error');
      expect(updated.error, 'new error');
    });
  });

  // ==========================================
  // EventCalendarNotifier
  // ==========================================

  group('EventCalendarNotifier', () {
    test('initial state is empty', () {
      final state = container.read(eventCalendarProvider);
      expect(state.focusedMonth, isNull);
      expect(state.isLoading, isFalse);
    });

    test('init sets focused month and selected date', () async {
      when(
        () => mockEventRepo.getEventsInRange(
          any(),
          any(),
          symbols: any(named: 'symbols'),
        ),
      ).thenAnswer((_) async => []);

      final notifier = container.read(eventCalendarProvider.notifier);
      await notifier.init();

      final state = container.read(eventCalendarProvider);
      expect(state.focusedMonth, DateTime(2026, 2));
      expect(state.selectedDate, isNotNull);
      expect(state.isLoading, isFalse);
    });

    test('loadMonthEvents loads events and groups by date', () async {
      final events = [
        createEvent(id: 1, eventDate: DateTime(2026, 2, 10), title: 'Event A'),
        createEvent(id: 2, eventDate: DateTime(2026, 2, 10), title: 'Event B'),
        createEvent(id: 3, eventDate: DateTime(2026, 2, 20), title: 'Event C'),
      ];

      when(
        () => mockEventRepo.getEventsInRange(
          any(),
          any(),
          symbols: any(named: 'symbols'),
        ),
      ).thenAnswer((_) async => events);

      final notifier = container.read(eventCalendarProvider.notifier);
      await notifier.loadMonthEvents(DateTime(2026, 2));

      final state = container.read(eventCalendarProvider);
      expect(state.isLoading, isFalse);
      expect(state.events.keys, hasLength(2)); // 2 distinct dates
      expect(state.error, isNull);
    });

    test('loadMonthEvents handles error', () async {
      when(
        () => mockEventRepo.getEventsInRange(
          any(),
          any(),
          symbols: any(named: 'symbols'),
        ),
      ).thenThrow(Exception('DB error'));

      final notifier = container.read(eventCalendarProvider.notifier);
      await notifier.loadMonthEvents(DateTime(2026, 2));

      final state = container.read(eventCalendarProvider);
      expect(state.isLoading, isFalse);
      expect(state.error, isNotNull);
    });

    test('selectDate updates selected date', () async {
      // First init to populate events
      when(
        () => mockEventRepo.getEventsInRange(
          any(),
          any(),
          symbols: any(named: 'symbols'),
        ),
      ).thenAnswer((_) async => []);

      final notifier = container.read(eventCalendarProvider.notifier);
      await notifier.init();

      notifier.selectDate(DateTime(2026, 2, 20));

      final state = container.read(eventCalendarProvider);
      expect(state.selectedDate, DateTime(2026, 2, 20));
    });

    test('setFilter changes filter and reloads', () async {
      when(
        () => mockEventRepo.getEventsInRange(
          any(),
          any(),
          symbols: any(named: 'symbols'),
        ),
      ).thenAnswer((_) async => []);

      final notifier = container.read(eventCalendarProvider.notifier);
      await notifier.init();

      // 預設已是 watchlistOnly（init 就會讀 watchlist），改切 portfolioOnly
      // 驗證換 filter 會以新範圍重載
      when(() => mockDb.getPortfolioPositions()).thenAnswer((_) async => []);

      await notifier.setFilter(CalendarFilter.portfolioOnly);

      final state = container.read(eventCalendarProvider);
      expect(state.filter, CalendarFilter.portfolioOnly);
      // 月載入＋upcoming 刷新各解析一次 portfolio symbols
      verify(() => mockDb.getPortfolioPositions()).called(2);
    });

    test('addEvent calls repository and reloads', () async {
      when(
        () => mockEventRepo.getEventsInRange(
          any(),
          any(),
          symbols: any(named: 'symbols'),
        ),
      ).thenAnswer((_) async => []);
      when(
        () => mockEventRepo.addCustomEvent(
          symbol: any(named: 'symbol'),
          eventDate: any(named: 'eventDate'),
          title: any(named: 'title'),
          description: any(named: 'description'),
        ),
      ).thenAnswer((_) async => 1);

      final notifier = container.read(eventCalendarProvider.notifier);
      await notifier.init();

      await notifier.addEvent(
        eventDate: DateTime(2026, 3, 1),
        title: 'My Event',
      );

      verify(
        () => mockEventRepo.addCustomEvent(
          symbol: null,
          eventDate: DateTime(2026, 3, 1),
          title: 'My Event',
          description: null,
        ),
      ).called(1);
    });

    test('deleteEvent calls repository and reloads', () async {
      when(
        () => mockEventRepo.getEventsInRange(
          any(),
          any(),
          symbols: any(named: 'symbols'),
        ),
      ).thenAnswer((_) async => []);
      when(() => mockEventRepo.deleteEvent(any())).thenAnswer((_) async {});

      final notifier = container.read(eventCalendarProvider.notifier);
      await notifier.init();

      await notifier.deleteEvent(42);

      verify(() => mockEventRepo.deleteEvent(42)).called(1);
    });

    test('syncDividendEvents calls repository', () async {
      when(
        () => mockEventRepo.getEventsInRange(
          any(),
          any(),
          symbols: any(named: 'symbols'),
        ),
      ).thenAnswer((_) async => []);
      when(
        () => mockEventRepo.syncDividendEvents(),
      ).thenAnswer((_) async => (exDividend: 3, exRights: 2, total: 5));

      final notifier = container.read(eventCalendarProvider.notifier);
      await notifier.init();

      final result = await notifier.syncDividendEvents();

      expect(result.total, 5);
      expect(result.exDividend, 3);
      expect(result.exRights, 2);
      verify(() => mockEventRepo.syncDividendEvents()).called(1);
      verify(() => mockEventRepo.syncDisposalEndEvents()).called(1);
      verify(() => mockEventRepo.syncShortSuspensionEvents()).called(1);
      verify(() => mockEventRepo.syncInvestorConferenceEvents()).called(1);
    });

    test('🚨 附帶來源失敗要列在 failedSources——半殘不得報成功(靜默稽核 #8)', () async {
      // 這顆按鈕是停券預告/法說會/處置出關唯一的同步入口(daily pipeline
      // 不呼叫);失敗只 log 的話,該類事件永遠停在舊狀態而 snackbar 照報
      // 成功——「行事曆上沒有停券事件」與「同步掛了」不可分。
      when(
        () => mockEventRepo.getEventsInRange(
          any(),
          any(),
          symbols: any(named: 'symbols'),
        ),
      ).thenAnswer((_) async => []);
      when(
        () => mockEventRepo.syncDividendEvents(),
      ).thenAnswer((_) async => (exDividend: 3, exRights: 2, total: 5));
      when(
        () => mockEventRepo.syncShortSuspensionEvents(),
      ).thenThrow(Exception('BFI84U down'));
      when(
        () => mockEventRepo.syncInvestorConferenceEvents(),
      ).thenThrow(Exception('t187ap04_L down'));

      final notifier = container.read(eventCalendarProvider.notifier);
      await notifier.init();
      final result = await notifier.syncDividendEvents();

      expect(result.total, 5, reason: '除權息結果不得被附帶失敗吞掉');
      expect(result.failedSources, [
        'shortSuspension',
        'investorConference',
      ], reason: '哪些來源半殘要說出來,snackbar 據此顯示');
    });

    test('附帶來源全成功 → failedSources 為空(不誤報)', () async {
      when(
        () => mockEventRepo.getEventsInRange(
          any(),
          any(),
          symbols: any(named: 'symbols'),
        ),
      ).thenAnswer((_) async => []);
      when(
        () => mockEventRepo.syncDividendEvents(),
      ).thenAnswer((_) async => (exDividend: 1, exRights: 0, total: 1));

      final notifier = container.read(eventCalendarProvider.notifier);
      await notifier.init();
      final result = await notifier.syncDividendEvents();
      expect(result.failedSources, isEmpty);
    });

    test('disposal 出關同步失敗不吞除權息結果（fail-soft）', () async {
      when(
        () => mockEventRepo.syncDividendEvents(),
      ).thenAnswer((_) async => (exDividend: 2, exRights: 1, total: 3));
      when(
        () => mockEventRepo.syncDisposalEndEvents(),
      ).thenThrow(Exception('db boom'));

      final notifier = container.read(eventCalendarProvider.notifier);
      final result = await notifier.syncDividendEvents();

      expect(result.total, 3, reason: '出關同步炸掉不得影響除權息結果');
      expect(
        container.read(eventCalendarProvider).isSyncing,
        isFalse,
        reason: 'isSyncing 必須復位',
      );
    });
  });

  // ==========================================
  // Provider declaration
  // ==========================================

  group('eventCalendarProvider', () {
    test('has correct initial state', () {
      final state = container.read(eventCalendarProvider);
      expect(state.events, isEmpty);
      expect(state.isLoading, isFalse);
      expect(state.error, isNull);
      expect(state.filter, CalendarFilter.watchlistOnly);
    });
  });

  // ==========================================
  // loadMonthEvents — stale month response discarded
  // ==========================================

  group('loadMonthEvents generation token', () {
    test('stale month response does not overwrite newer month', () async {
      final febEvents = [
        createEvent(id: 1, eventDate: DateTime(2026, 2, 10), title: 'Feb'),
      ];
      final marEvents = [
        createEvent(id: 2, eventDate: DateTime(2026, 3, 5), title: 'Mar'),
      ];

      // 用 Completer 控制 2 月載入的完成時機
      final febCompleter = Completer<List<StockEventEntry>>();
      // 依請求月份分流（不能用 callCount：watchlistOnly 預設下
      // loadMonthEvents 先 await getWatchlist，落後的 2 月請求會被
      // generation 檢查提前棄單、根本不會打 getEventsInRange）
      when(
        () => mockEventRepo.getEventsInRange(
          any(),
          any(),
          symbols: any(named: 'symbols'),
        ),
      ).thenAnswer((inv) {
        final start = inv.positionalArguments[0] as DateTime;
        // 只有「2 月的月載入」（起始 2/1）走 completer；upcoming 範圍
        // （起始＝今天 2/15，setFilter 會刷新）回空，避免互相卡死
        if (start == DateTime(2026, 2, 1)) return febCompleter.future;
        if (start == DateTime(2026, 2, 15)) {
          return Future.value(<StockEventEntry>[]);
        }
        return Future.value(marEvents); // 3 月：立即完成
      });

      final notifier = container.read(eventCalendarProvider.notifier);
      // 切到 all：watchlistOnly 會先 await getWatchlist，落後請求在
      // 「fetch 前」的 generation 檢查就被棄單，測不到「fetch 慢回來」
      // 的 late-response guard（本測試的原始意圖）
      await notifier.setFilter(CalendarFilter.all);

      // 先載入 2 月（不 await），再立刻切到 3 月
      final febFuture = notifier.loadMonthEvents(DateTime(2026, 2));
      final marFuture = notifier.loadMonthEvents(DateTime(2026, 3));

      // 3 月先完成
      await marFuture;
      expect(
        container.read(eventCalendarProvider).focusedMonth,
        DateTime(2026, 3),
      );

      // 2 月晚回來
      febCompleter.complete(febEvents);
      await febFuture;

      // 最終 state 應該是 3 月，不被 2 月覆蓋
      final state = container.read(eventCalendarProvider);
      expect(state.focusedMonth, DateTime(2026, 3));
      expect(state.events.values.expand((e) => e).first.title, 'Mar');
    });
  });
}
